#ifndef CONSTANT_H_
#define CONSTANT_H_
#define RADIUS        (6371000.)
#define STRING        255
#define STRING_NAME        "string"
#define MOSAIC_NAME        "mosaic"
#define NTILES_NAME        "ntiles"
#define NMOSAIC_NAME       "nmosaic"
#define NCONTACT_NAME      "ncontact"
#define TILE_FILES_NAME    "tile_files"
#define MOSAIC_FILES_NAME  "mosaic_files"
#define CONTACT_FILES_NAME "contact_files"
#define OVERLAP_FILES_NAME "overlap_files"
#define TILE_NAME          "tile"
#define NX_NAME            "nx"
#define NY_NAME            "ny"
#define NXP_NAME           "nxp"
#define NYP_NAME           "nyp"
#define X_NAME             "x"
#define Y_NAME             "y"
#define DX_NAME            "dx"
#define DY_NAME            "dy"
#define ANGLE_DX_NAME      "angle_dx"
#define ANGLE_DY_NAME      "angle_dy"
#define ARCX_NAME          "arcx"
#define DEPTH_NAME         "depth"
#define MASK_NAME          "area_frac"
#define NZV_NAME           "nzv"
#define ZETA_NAME          "zeta"
#define GRID_VERSION_NAME  "grid_version"
#define CODE_VERSION_NAME  "code_version"
#define HISTORY_NAME       "history"
#define CONFORMAL_NAME     "isConformal"
#define REGULAR_NAME       "isRegular"
#define DISCRETIZATION_NAME "discretizationType"
#define GEOMETRY_NAME       "geometryType"
#define CONGRUCENCE_NAME    "congruentTiles"
#endif
