/* $Id$
 *
 * Copyright (c) 2012-2013
 * by P. Wessel, W. H. F. Smith, R. Scharroo, J. Luis, and F. Wobbe
 * See LICENSE.TXT file for copying and redistribution conditions.
 */

/* gmt_supplmodule.h declares the prototypes for suppl module functions
 * and the array that contains suppl GMT module parameters such as name and purpose strings.
 * DO NOT edit this file directly! Instead edit gmt_supplmoduleinfo.txt and regenerate
 * this file with gmt_make_module_src.sh suppl. */

#pragma once
#ifndef _GMT_SUPPLMODULE_H
#define _GMT_SUPPLMODULE_H

#ifdef __cplusplus /* Basic C++ support */
extern "C" {
#endif

/* CMake definitions: This must be first! */
#include "gmt_config.h"

/* Declaration modifiers for DLL support (MSC et al) */
#include "declspec.h"

/* external array with program parameters for all GMT modules */
EXTERN_MSC struct Gmt_moduleinfo g_supplmodule[];

EXTERN_MSC int GMT_backtracker (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_dimfilter (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_gmtgravmag3d (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_gravfft (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdgravmag3d (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdpmodeler (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdredpol (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdrotater (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdseamount (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_grdspotter (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_gshhg (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_hotspotter (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_img2grd (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77convert (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77info (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77list (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77magref (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77manage (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77path (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77sniffer (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_mgd77track (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_originator (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_pscoupe (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_psmeca (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_pspolar (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_pssegy (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_pssegyz (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_psvelo (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_rotconverter (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_segy2grd (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_binlist (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_cross (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_datalist (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_get (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_init (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_list (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_merge (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_put (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_report (void *api_ctrl, int mode, void *args);
EXTERN_MSC int GMT_x2sys_solve (void *api_ctrl, int mode, void *args);

/* Pretty print all module names and their purposes */
EXTERN_MSC void gmt_supplmodule_show_all (struct GMTAPI_CTRL *API);

#ifdef __cplusplus
}
#endif

#endif /* !_GMT_SUPPLMODULE_H */
