/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  /opt/local/bin/gengetopt --no-version --no-help -l --input=gmt_project.ggo --unamed-opts=table --no-handle-error --no-handle-help --no-handle-version --func-name=gmt_cmdline_parser --file-name=gmt_cmdline_project

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "gmt_cmdline_project.h"

const char *gengetopt_args_info_purpose = "Project table data onto lines or great circles, generate tracks, or translate \ncoordinates";

const char *gengetopt_args_info_usage = "Usage: project -Ccx/cy|--center=cx/cy [-Aazimuth|--azimuth=azimuth] \n         [-Eex/ey|--endpoint=ex/ey] [-Tpx/py|--pole=px/py] [-?|--help] \n         [--full-help] [-^|--detailed-help] [--version] [table]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_detailed_help[] = {
  "Mandatory arguments:",
  "  -C, --center=cx/cy       The origin of the projection",
  "\n Group: projection\n  The projection may be defined in (only) one of three ways:",
  "  -A, --azimuth=azimuth    Azimuth in degrees clockwise from North",
  "  -E, --endpoint=ex/ey     End point of the projection path",
  "  -T, --pole=px/py         Position of the rotation pole of the projection",
  "\nAdditional arguments:",
  "  -V, --verbose[=level]    Change the verbosity level  (default=`1')",
  "  Choose among 5 levels; each level adds more messages:\n     0 - Complete silence, not even fatal error messages\n     1 - Fatal error messages [Default when no -V is used]\n     2 - Warnings and progress messages [Default when -V is used]\n     3 - Detailed progress messages\n     4 - Debugging messages",
  "  -c, --copies[=ncopies]   Specify the number of copies  (default=`1')",
  "  -h, --header[=[i|o][n]]  Input file has header records",
  "  -/, --swap[=[i|o]]       Swap 1st and 2nd column on input and/or output",
  "      --output=[outfile]   Output file  (default=`stdout')",
  "\nHelp:",
  "  -?, --help               Show help (required arguments only), and exit",
  "      --full-help          Show help, including hidden options, and exit",
  "  -^, --detailed-help      Show help, including all details and hidden options, \n                             and exit",
  "      --version            Print version and exit",
  "\nPlease refer to the manual for further explanations.",
    0
};
static void
init_full_help_array(void)
{
  gengetopt_args_info_full_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_full_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_full_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_full_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_full_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_full_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_full_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_full_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_full_help[8] = gengetopt_args_info_detailed_help[9];
  gengetopt_args_info_full_help[9] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_full_help[10] = gengetopt_args_info_detailed_help[11];
  gengetopt_args_info_full_help[11] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_full_help[12] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_full_help[13] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_full_help[14] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_full_help[15] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_full_help[16] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_full_help[17] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_full_help[18] = 0; 
  
}

const char *gengetopt_args_info_full_help[19];

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_help[7] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_help[8] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_help[9] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_help[10] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_help[11] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_help[12] = 0; 
  
}

const char *gengetopt_args_info_help[13];

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
} gmt_cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
gmt_cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct gmt_cmdline_parser_params *params, const char *additional_error);

static int
gmt_cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->center_given = 0 ;
  args_info->azimuth_given = 0 ;
  args_info->endpoint_given = 0 ;
  args_info->pole_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->copies_given = 0 ;
  args_info->header_given = 0 ;
  args_info->swap_given = 0 ;
  args_info->output_given = 0 ;
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->detailed_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->projection_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->center_arg = NULL;
  args_info->center_orig = NULL;
  args_info->azimuth_arg = NULL;
  args_info->azimuth_orig = NULL;
  args_info->endpoint_arg = NULL;
  args_info->endpoint_orig = NULL;
  args_info->pole_arg = NULL;
  args_info->pole_orig = NULL;
  args_info->verbose_arg = 1;
  args_info->verbose_orig = NULL;
  args_info->copies_arg = 1;
  args_info->copies_orig = NULL;
  args_info->header_arg = NULL;
  args_info->header_orig = NULL;
  args_info->swap_arg = NULL;
  args_info->swap_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  init_full_help_array(); 
  init_help_array(); 
  args_info->center_help = gengetopt_args_info_detailed_help[1] ;
  args_info->azimuth_help = gengetopt_args_info_detailed_help[3] ;
  args_info->endpoint_help = gengetopt_args_info_detailed_help[4] ;
  args_info->pole_help = gengetopt_args_info_detailed_help[5] ;
  args_info->verbose_help = gengetopt_args_info_detailed_help[7] ;
  args_info->copies_help = gengetopt_args_info_detailed_help[9] ;
  args_info->header_help = gengetopt_args_info_detailed_help[10] ;
  args_info->swap_help = gengetopt_args_info_detailed_help[11] ;
  args_info->output_help = gengetopt_args_info_detailed_help[12] ;
  args_info->help_help = gengetopt_args_info_detailed_help[14] ;
  args_info->full_help_help = gengetopt_args_info_detailed_help[15] ;
  args_info->detailed_help_help = gengetopt_args_info_detailed_help[16] ;
  args_info->version_help = gengetopt_args_info_detailed_help[17] ;
  
}

void
gmt_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(GMT_CMDLINE_PARSER_PACKAGE_NAME) ? GMT_CMDLINE_PARSER_PACKAGE_NAME : GMT_CMDLINE_PARSER_PACKAGE),
     GMT_CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  gmt_cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
gmt_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
gmt_cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
gmt_cmdline_parser_print_detailed_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_detailed_help[i])
    printf("%s\n", gengetopt_args_info_detailed_help[i++]);
}

void
gmt_cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
gmt_cmdline_parser_params_init(struct gmt_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct gmt_cmdline_parser_params *
gmt_cmdline_parser_params_create(void)
{
  struct gmt_cmdline_parser_params *params = 
    (struct gmt_cmdline_parser_params *)malloc(sizeof(struct gmt_cmdline_parser_params));
  gmt_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
gmt_cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->center_arg));
  free_string_field (&(args_info->center_orig));
  free_string_field (&(args_info->azimuth_arg));
  free_string_field (&(args_info->azimuth_orig));
  free_string_field (&(args_info->endpoint_arg));
  free_string_field (&(args_info->endpoint_orig));
  free_string_field (&(args_info->pole_arg));
  free_string_field (&(args_info->pole_orig));
  free_string_field (&(args_info->verbose_orig));
  free_string_field (&(args_info->copies_orig));
  free_string_field (&(args_info->header_arg));
  free_string_field (&(args_info->header_orig));
  free_string_field (&(args_info->swap_arg));
  free_string_field (&(args_info->swap_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
gmt_cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", GMT_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->center_given)
    write_into_file(outfile, "center", args_info->center_orig, 0);
  if (args_info->azimuth_given)
    write_into_file(outfile, "azimuth", args_info->azimuth_orig, 0);
  if (args_info->endpoint_given)
    write_into_file(outfile, "endpoint", args_info->endpoint_orig, 0);
  if (args_info->pole_given)
    write_into_file(outfile, "pole", args_info->pole_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  if (args_info->copies_given)
    write_into_file(outfile, "copies", args_info->copies_orig, 0);
  if (args_info->header_given)
    write_into_file(outfile, "header", args_info->header_orig, 0);
  if (args_info->swap_given)
    write_into_file(outfile, "swap", args_info->swap_orig, 0);
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->detailed_help_given)
    write_into_file(outfile, "detailed-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
gmt_cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", GMT_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = gmt_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
gmt_cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  gmt_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_projection(struct gengetopt_args_info *args_info)
{
  if (! args_info->projection_group_counter)
    return;
  
  args_info->azimuth_given = 0 ;
  free_string_field (&(args_info->azimuth_arg));
  free_string_field (&(args_info->azimuth_orig));
  args_info->endpoint_given = 0 ;
  free_string_field (&(args_info->endpoint_arg));
  free_string_field (&(args_info->endpoint_orig));
  args_info->pole_given = 0 ;
  free_string_field (&(args_info->pole_arg));
  free_string_field (&(args_info->pole_orig));

  args_info->projection_group_counter = 0;
}

int
gmt_cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return gmt_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
gmt_cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct gmt_cmdline_parser_params *params)
{
  int result;
  result = gmt_cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
gmt_cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct gmt_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = gmt_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
gmt_cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (gmt_cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
gmt_cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->center_given)
    {
      fprintf (stderr, "%s: '--center' ('-C') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->projection_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group projection were given. One is required%s.\n", prog_name, args_info->projection_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  

  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see gmt_cmdline_parser_params.check_ambiguity
 * @param override @see gmt_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               gmt_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
gmt_cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct gmt_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    gmt_cmdline_parser_init (args_info);

  gmt_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "center",	1, NULL, 'C' },
        { "azimuth",	1, NULL, 'A' },
        { "endpoint",	1, NULL, 'E' },
        { "pole",	1, NULL, 'T' },
        { "verbose",	2, NULL, 'V' },
        { "copies",	2, NULL, 'c' },
        { "header",	2, NULL, 'h' },
        { "swap",	2, NULL, '/' },
        { "output",	1, NULL, 0 },
        { "help",	0, NULL, '?' },
        { "full-help",	0, NULL, 0 },
        { "detailed-help",	0, NULL, '^' },
        { "version",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "C:A:E:T:V::c::h::/::?^", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'C':	/* The origin of the projection.  */
        
        
          if (update_arg( (void *)&(args_info->center_arg), 
               &(args_info->center_orig), &(args_info->center_given),
              &(local_args_info.center_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "center", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'A':	/* Azimuth in degrees clockwise from North.  */
        
          if (args_info->projection_group_counter && override)
            reset_group_projection (args_info);
          args_info->projection_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->azimuth_arg), 
               &(args_info->azimuth_orig), &(args_info->azimuth_given),
              &(local_args_info.azimuth_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "azimuth", 'A',
              additional_error))
            goto failure;
        
          break;
        case 'E':	/* End point of the projection path.  */
        
          if (args_info->projection_group_counter && override)
            reset_group_projection (args_info);
          args_info->projection_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->endpoint_arg), 
               &(args_info->endpoint_orig), &(args_info->endpoint_given),
              &(local_args_info.endpoint_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "endpoint", 'E',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Position of the rotation pole of the projection.  */
        
          if (args_info->projection_group_counter && override)
            reset_group_projection (args_info);
          args_info->projection_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->pole_arg), 
               &(args_info->pole_orig), &(args_info->pole_given),
              &(local_args_info.pole_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "pole", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'V':	/* Change the verbosity level.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'V',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Specify the number of copies.  */
        
        
          if (update_arg( (void *)&(args_info->copies_arg), 
               &(args_info->copies_orig), &(args_info->copies_given),
              &(local_args_info.copies_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "copies", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'h':	/* Input file has header records.  */
        
        
          if (update_arg( (void *)&(args_info->header_arg), 
               &(args_info->header_orig), &(args_info->header_given),
              &(local_args_info.header_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "header", 'h',
              additional_error))
            goto failure;
        
          break;
        case '/':	/* Swap 1st and 2nd column on input and/or output.  */
        
        
          if (update_arg( (void *)&(args_info->swap_arg), 
               &(args_info->swap_orig), &(args_info->swap_given),
              &(local_args_info.swap_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "swap", '/',
              additional_error))
            goto failure;
        
          break;
        case '?':	/* Show help (required arguments only), and exit.  */
        
          if (optopt) /* '?' represents an unrecognized option */
            goto failure;
        
        
          if (update_arg( 0 , 
               0 , &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "help", '?',
              additional_error))
            goto failure;
        
          break;
        case '^':	/* Show help, including all details and hidden options, and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->detailed_help_given),
              &(local_args_info.detailed_help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "detailed-help", '^',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Output file  (default=`stdout').  */
          if (strcmp (long_options[option_index].name, "output") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->output_arg), 
                 &(args_info->output_orig), &(args_info->output_given),
                &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "output", '-',
                additional_error))
              goto failure;
          
          }
          /* Show help, including hidden options, and exit.  */
          else if (strcmp (long_options[option_index].name, "full-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->full_help_given),
                &(local_args_info.full_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "full-help", '-',
                additional_error))
              goto failure;
          
          }
          /* Print version and exit.  */
          else if (strcmp (long_options[option_index].name, "version") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->version_given),
                &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "version", '-',
                additional_error))
              goto failure;
          
          }
          
          break;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", GMT_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->projection_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group projection were given. One is required%s.\n", argv[0], args_info->projection_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += gmt_cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  gmt_cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  gmt_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
