/** @file gmt_cmdline_project.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef GMT_CMDLINE_PROJECT_H
#define GMT_CMDLINE_PROJECT_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef GMT_CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define GMT_CMDLINE_PARSER_PACKAGE "project"
#endif

#ifndef GMT_CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define GMT_CMDLINE_PARSER_PACKAGE_NAME "project"
#endif

#ifndef GMT_CMDLINE_PARSER_VERSION
/** @brief the program version */
#define GMT_CMDLINE_PARSER_VERSION "5.0.2"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  char * center_arg;	/**< @brief The origin of the projection.  */
  char * center_orig;	/**< @brief The origin of the projection original value given at command line.  */
  const char *center_help; /**< @brief The origin of the projection help description.  */
  char * azimuth_arg;	/**< @brief Azimuth in degrees clockwise from North.  */
  char * azimuth_orig;	/**< @brief Azimuth in degrees clockwise from North original value given at command line.  */
  const char *azimuth_help; /**< @brief Azimuth in degrees clockwise from North help description.  */
  char * endpoint_arg;	/**< @brief End point of the projection path.  */
  char * endpoint_orig;	/**< @brief End point of the projection path original value given at command line.  */
  const char *endpoint_help; /**< @brief End point of the projection path help description.  */
  char * pole_arg;	/**< @brief Position of the rotation pole of the projection.  */
  char * pole_orig;	/**< @brief Position of the rotation pole of the projection original value given at command line.  */
  const char *pole_help; /**< @brief Position of the rotation pole of the projection help description.  */
  int verbose_arg;	/**< @brief Change the verbosity level (default='1').  */
  char * verbose_orig;	/**< @brief Change the verbosity level original value given at command line.  */
  const char *verbose_help; /**< @brief Change the verbosity level help description.  */
  int copies_arg;	/**< @brief Specify the number of copies (default='1').  */
  char * copies_orig;	/**< @brief Specify the number of copies original value given at command line.  */
  const char *copies_help; /**< @brief Specify the number of copies help description.  */
  char * header_arg;	/**< @brief Input file has header records.  */
  char * header_orig;	/**< @brief Input file has header records original value given at command line.  */
  const char *header_help; /**< @brief Input file has header records help description.  */
  char * swap_arg;	/**< @brief Swap 1st and 2nd column on input and/or output.  */
  char * swap_orig;	/**< @brief Swap 1st and 2nd column on input and/or output original value given at command line.  */
  const char *swap_help; /**< @brief Swap 1st and 2nd column on input and/or output help description.  */
  char * output_arg;	/**< @brief Output file  (default=`stdout').  */
  char * output_orig;	/**< @brief Output file  (default=`stdout') original value given at command line.  */
  const char *output_help; /**< @brief Output file  (default=`stdout') help description.  */
  const char *help_help; /**< @brief Show help (required arguments only), and exit help description.  */
  const char *full_help_help; /**< @brief Show help, including hidden options, and exit help description.  */
  const char *detailed_help_help; /**< @brief Show help, including all details and hidden options, and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  
  unsigned int center_given ;	/**< @brief Whether center was given.  */
  unsigned int azimuth_given ;	/**< @brief Whether azimuth was given.  */
  unsigned int endpoint_given ;	/**< @brief Whether endpoint was given.  */
  unsigned int pole_given ;	/**< @brief Whether pole was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */
  unsigned int copies_given ;	/**< @brief Whether copies was given.  */
  unsigned int header_given ;	/**< @brief Whether header was given.  */
  unsigned int swap_given ;	/**< @brief Whether swap was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int full_help_given ;	/**< @brief Whether full-help was given.  */
  unsigned int detailed_help_given ;	/**< @brief Whether detailed-help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
  int projection_group_counter; /**< @brief Counter for group projection */
} ;

/** @brief The additional parameters to pass to parser functions */
struct gmt_cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];
/** @brief all the lines making the full help output (including hidden options) */
extern const char *gengetopt_args_info_full_help[];
/** @brief all the lines making the detailed help output (including hidden options and details) */
extern const char *gengetopt_args_info_detailed_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int gmt_cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use gmt_cmdline_parser_ext() instead
 */
int gmt_cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int gmt_cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct gmt_cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int gmt_cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int gmt_cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void gmt_cmdline_parser_print_help(void);
/**
 * Print the full help (including hidden options)
 */
void gmt_cmdline_parser_print_full_help(void);
/**
 * Print the detailed help (including hidden options and details)
 */
void gmt_cmdline_parser_print_detailed_help(void);
/**
 * Print the version
 */
void gmt_cmdline_parser_print_version(void);

/**
 * Initializes all the fields a gmt_cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void gmt_cmdline_parser_params_init(struct gmt_cmdline_parser_params *params);

/**
 * Allocates dynamically a gmt_cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized gmt_cmdline_parser_params structure
 */
struct gmt_cmdline_parser_params *gmt_cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void gmt_cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void gmt_cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int gmt_cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* GMT_CMDLINE_PROJECT_H */
