#-------------------------------------------------------------------------------
#  $Id: GNUmakefile,v 1.1 2007-09-25 01:50:16 remko Exp $
#
#	Guru Makefile for GMT Version 4.x mgg directory
#	
#	!!! THIS MAKEFILE IS FOR GMT DEVELOPERS ONLY !!!
#
#	This makefile extends the regular Makefile by adding the
#	dependencies needed to generate certain source files from
#	lower-level data files available in CVS but not in archives.
#
#	Author:	Paul Wessel, SOEST, University of Hawaii
#
#	Date:		24-SEP-2007
#-------------------------------------------------------------------------------

include ../../guru/gmtguru.macros.orig	# Overall default guru settings
sinclude ../../guru/gmtguru.macros	# Guru-specific settings determined by GURU

include makefile
include ../manpages.mk
