# Configuration for welcome bot - https://github.com/behaviorbot/welcome
########################################################################################
# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  👋 Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. We appreciate that you took the time to contribute!

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  💖 Thanks for opening this pull request! 💖

  A few things to keep in mind:

  * If you need help writing tests, take a look at the existing ones for inspiration. If you don't know where to start, let us know and we'll walk you through it.
  * All new features should be documented. It helps to write the comments below for your functions describing the it, **all** arguments, and return types before writing the code. This will help you think about your code design and results in better code.
  * We are grateful that you put in the effort to do this! 🎉

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  🎉🎉🎉 Congrats on merging your first pull request and welcome to the team! 🎉🎉🎉

  We hope that this was a good experience for you. Let us know if there is any way that the contributing process could be improved.
