# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Allow up to 2 open pull requests at a time
    open-pull-requests-limit: 2
    # Specify labels for pull requests
    labels:
      - "maintenance"

  - package-ecosystem: "pip"
    directory: "/doc/rst/"
    schedule:
      interval: "monthly"
    # Allow up to 2 open pull requests at a time
    open-pull-requests-limit: 2
    # Specify labels for pull requests
    labels:
      - "maintenance"
