name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  minor:
    labels:
      - 'feature'
  default: patch
categories:
  - title: 'New Features'
    label: 'new feature'
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'maintenance'
include-labels:
  - 'add-changelog'
category-template: '### $TITLE'
change-template: '* $TITLE ([#$NUMBER]($URL))'
template: |
  ## Release of GMT $RESOLVED_VERSION

  ### Highlights

  *

  $CHANGES

  ### Contributors

  $CONTRIBUTORS
