#!/bin/sh
#
#	$Id: mgd77netcdfhelper.sh,v 1.1 2005-10-14 05:12:14 pwessel Exp $
#
#	Author:	P. Wessel
#	Date:	2005-OCT-13
#
# This script will create two functions from info in mgd77.h:
#
# MGD77_Read_Header_Params	: Read the MGD77 header attributes from the netCDF file
# MGD77_Write_Header_Params	: Write the MGD77 header attributes from the netCDF file
#
# Code is placed in the file mgd77_functions.h which is included in mgd77.c
#

stem=""
cat << EOF > mgd77_functions.h

/* START OF CODE GENERATED BY mgd77netcdfhelper.sh */

void MGD77_Read_Header_Params (struct MGD77_CONTROL *F, struct MGD77_HEADER_PARAMS *P)
{
	/* Read the netCDF-encoded MGD77 header parameters as attributes of the data set */
	
EOF
# 1. strip out the structure members only, then replace brackets and ; with space to simplify processing in the loop below */
sed -n '/START OF MGD77_HEADER_PARAMS/,/END OF MGD77_HEADER_PARAMS/p' mgd77.h | egrep -v 'OF MGD77_HEADER_PARAMS|Sequence No' | tr '[];' '   ' > $$.1
while read type name L M; do		# We need a separate read/write statement for each attribute
	pre=""				# Normally, no prefix for character arrays
	cast=""
	if [ "X$L" = "X" ]; then	# No number means a single character
		length=1
		pre="&"			# We need to take address of a single char
	elif [ "X$M" = "X" ]; then	# Single text length given
		length=$L
		length="strlen (${pre}P->${stem}$name)"
	else				# 2-D text array, dim and length given, calc total size
		length=`gmtmath -Q $M $L MUL =`
		cast="(char *)"
	fi
	echo "	MGD77_nc_status (nc_get_att_text (F->nc_id, NC_GLOBAL, "\"$name\"", ${cast}${pre}P->${stem}$name));" >> mgd77_functions.h
	echo "	MGD77_nc_status (nc_put_att_text (F->nc_id, NC_GLOBAL, "\"$name\"", $length, ${cast}${pre}P->${stem}$name));" >> $$.2
done < $$.1
cat << EOF >> mgd77_functions.h

}

void MGD77_Write_Header_Params (struct MGD77_CONTROL *F, struct MGD77_HEADER_PARAMS *P)
{
	/* Write the MGD77 header parameters as attributes of the netCDF-encoded data set */
	
EOF
cat $$.2 >> mgd77_functions.h
cat << EOF >> mgd77_functions.h

}

/* END OF CODE GENERATED BY mgd77netcdfhelper.sh */

EOF

rm -f $$.*
echo "mgd77netcdfhelper.sh: mgd77_functions.h created"
