Attributes {
    TIME {
        String units "hour";
        String time_origin "1-JAN-0000 00:00:00";
        String modulo " ";
    }
    SST {
        Float32 missing_value -9.999999790e+33;
        Float32 _FillValue -9.999999790e+33;
        String long_name "SEA SURFACE TEMPERATURE";
        String long_name_mod "X=0E(360)@ITP, Y=0@ITP";
        String history "From coads-climatology";
        String units "Deg C";
    }
    NC_GLOBAL {
        String history "FERRET V3.20 (development) 24-Jan-95";
    }
    DODS_EXTRA {
        String Unlimited_Dimension "TIME";
    }
}
