Attributes {
    aa {
        String units "furlongs";
    }
    bb {
        Float32 valid_range 0.000000000, 100.0000000;
    }
    cc {
        String units "moles";
    }
    cd {
        String units "moles";
    }
    ce {
        String units "moles";
    }
    dd {
        Int16 fill_value -999;
    }
    bytev {
    }
    charv {
    }
    shortv {
    }
    longv {
    }
    floatv {
    }
    doublev {
    }
    scalarv {
    }
    xx {
    }
    bytevar {
    }
    charvar {
    }
    shortvar {
    }
    longvar {
    }
    floatvar {
    }
    doublevar {
    }
    yy {
    }
    zz {
    }
    ww {
        String att0 "chars";
        Byte att1 97, 98;
        String att2 "chars";
        Int16 att3 -999, 0, 999;
        Int32 att4 10, 20;
        Float32 att5 1.500000000, 2.500000000, 3.500000000;
    }
    vv {
    }
    uu {
        Int32 valid_max 1000;
    }
    tt {
        Float64 att -1.0000000000000000, -2.0000000000000000;
    }
    tu {
        Float32 att -1.000000000, -2.000000000;
    }
    yet_another_variable {
        Int16 yet_another_attribute -1, -2, -3;
    }
    NC_GLOBAL {
        String title "test netcdf";
        Byte att0 97, 98;
        String att1 "chars";
        Int16 att2 -999, 0, 999;
        Int32 att3 10, 20;
        Float32 att4 1.500000000, 2.500000000, 3.500000000;
        Float64 att5 4.5000000000000000, 5.5000000000000000, 6.5000000000000000, 7.5000000000000000;
        Float32 att -1.000000000, -2.000000000;
        Int16 attx 3, 4, 5;
        Int16 plugh 3, 4, 5;
        Int16 longer_name 3, 4, 5;
        Int16 yet_another_attribute -1, -2, -3;
    }
    DODS_EXTRA {
        String Unlimited_Dimension "rec";
    }
}
