#-------------------------------------------------------------------------------
#  $Id: GNUmakefile,v 1.2 2007-11-14 20:27:29 remko Exp $
#
#	Guru Makefile for GMT Version 4.x dbase directory
#	
#	!!! THIS MAKEFILE IS FOR GMT DEVELOPERS ONLY !!!
#
#	This makefile extends the regular Makefile by adding the
#	dependencies needed to generate certain source files from
#	lower-level data files available in CVS but not in archives.
#
#	Author:	Paul Wessel, SOEST, University of Hawaii
#
#	Date:		24-SEP-2007
#-------------------------------------------------------------------------------

include makefile
include ../manpages.mk
