#-------------------------------------------------------------------------------
#  $Id$
#
#	Guru Makefile for GMT Version 5 dbase directory
#	
#	!!! THIS MAKEFILE IS FOR GMT DEVELOPERS ONLY !!!
#
#	This makefile extends the regular Makefile by adding the
#	dependencies needed to generate certain source files from
#	lower-level data files available in CVS but not in archives.
#
#	Author:	Paul Wessel, SOEST, University of Hawaii
#
#	Date:		20-APR-2010
#-------------------------------------------------------------------------------

include Makefile
include $(GMTSRCDIR)manpages.mk
