Attributes {
    b31 {
        class {
            String long_name "class is dismissed";
        }
        text {
            String long_name "textually yours";
        }
        foo {
            String long_name "It is beyond all recognition";
            String short_name "foobar";
        }
    }
    b32 {
        String billy "Bob is my real name";
        String Robert "Really wants to be called Billy";
    }
}
