/*
 * COPYRIGHT (c) 1993-2024 GEOWARE
 *
 * ttt.h
 *
 * PROGRAM:	ttt.h
 * PURPOSE:	Include file for ttt.c
 * AUTHOR:	Paul Wessel, GEOWARE
 * DATE:	June 16, 1993
 * UPDATED:	Jan 1, 2024
 * VERSION:	4.0
 */

#define TTT_YEAR 	"2024"	/* Latest ttt release year */
#define TTT_VER 	"4.0"	/* Latest ttt release version */

/*------------No further edits unless code change------------*/
#define _POSIX_SOURCE 1

/* Standard POSIX include files */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include <ctype.h>
#ifndef WIN32
#include <unistd.h>
#endif

/* Special non-POSIX (typically ANSI extensions) are handled in this
 * separate include file generated by a configure script - or if on
 * Windows we set it directly. */

#if TTT_SIZE_P == 8
	/* 64-bit version of TTT using 8-byte integers to accumulate travel time increments */
	#define TTT_VERSION 	TTT_VER " [64-bit]"	/* ttt version */
	#ifdef _WIN64
	#define TTT_LL "ll"
	#else
	typedef int64_t TTT_LONG;		/* A signed 8 byte integer under OSX/Linux/UNix 64-bit compilation */
	#define TTT_LL "l"
	#endif
	#define LAND		LONG_MAX	/* 9223372036854775807 (64-bit) */
	#define USED		(LONG_MAX - 1)	/* 9223372036854775806 (64-bit) */
	#define OCEAN		(LONG_MAX - 2)	/* 9223372036854775805 (64-bit) */
	#define T_UNIT		0.000000001	/* Integer unit of time in seconds (1 nanosec) for a max tt of ~292 years */
#else	/* TTT_SIZE_P == 4 */
	/* 32-bit version of TTT using 4-byte integers to accumulate travel time increments */
	#define TTT_VERSION 	TTT_VER " [32-bit]"	/* ttt version */
	typedef int TTT_LONG;		/* 4 bytes */
	#define TTT_LL ""	/* No modifier needed */
	#define LAND		INT_MAX		/* 2147483647 (32-bit) */
	#define USED		(INT_MAX - 1)	/* 2147483646 (32-bit) */
	#define OCEAN		(INT_MAX - 2)	/* 2147483645 (32-bit) */
	#define T_UNIT		0.0001		/* Integer unit of time in seconds (0.1 msec) for a max tt of ~119 hours */
#endif

#define N_PAD		13L	/* # of auxillary rows/columns */
#define N_CALC		120	/* Number of nodes to calculate itt's to */
#define M_ACCESS	256	/* Number of neighboring nodes accessed */
#define M_BITSETS	8	/* Number of 32-bit words needed to hold 256 bits */
#define	RADIUS		5.0	/* Search radius in degrees for epicenter */
#define DEGREE_TO_METER	(2.0 * M_PI * 6371007.181 / 360.0)	/* Radius of sphere with same surface area */
#define G_E		9.7803267715	/* The following three terms are used in normal grav equation */
#define G_C1		0.0052790414
#define G_C2		0.0000232718
#define	UNIT_TO_HOUR 	(T_UNIT / 3600.0)	/* Convert internal integer timings to hours */
#define TTT_BIT(no)		((unsigned int)(1 << ((no)%32)))
#define CHUNK		64
#define IJ(i,j,mx,pad) (((j)+(pad))*(mx)+(i)+(pad))

#define CONV_LIMIT	1.0e-8		/* "close to zero" limit */
#define ESRI_NAN	-999999.0	/* Used in ESRI flt files */

/* Macros for byte-order swapping 2- and 4-byte values (From John M. Kuhn, NOAA) */

#define TTT_swab2(data) ((((data) & 255) << 8) | ((unsigned short) (data) >> 8))
#define TTT_swab4(data) \
	(((data) << 24) | (((data) << 8) & 16711680) | \
	(((data) >> 8) & 65280) | ((unsigned int)(data) >> 24))

/* The next three functions have leading underscores on Windows.
 * We define them here and they will be picked up below */

/* Data structure definitions */

/* Reproduce GMT grid header to use in TTT */

#define TTT_IS_GMT_FLOAT	0
#define TTT_IS_GMT_SHORT	1
#define TTT_IS_GRIDFLOAT	2
#define TTT_IS_ESRIASCII	3

#define GMT_GRIDLINE_REG	0
#define GMT_PIXEL_REG		1
#define TTT_X	0
#define TTT_Y	1

struct TTT_INFO {	/* Binary tree node structure with travel time, node number and lower/higher nodes on tree */
	TTT_LONG tt, ij;
	struct TTT_INFO *l, *r;
};

/* ----------------------- GLOBAL VARIABLES BEGIN ----------------------- */

char *TTT_DIR = NULL;		/* Directory with .i2 files */
char *TTT_ext[5] = {"b", "i2", "hdr", "asc", "flt"};
char *TTT_wmode[5] = {"wb", "wb", "w", "w", "wb"};
char *TTT_rmode[5] = {"rb", "rb", "r", "r", "rb"};

unsigned int use_bits[M_BITSETS][N_CALC];	/* Array of bits indicating which nodes 0 <= k < 256 to use for each node */

/* All the following distances are normalized by the number of x-increments required */

double dy;	/* Constant distance (no array needed) between y-nodes [m(eters)] */
double *dx;	/* Distances between x-nodes as a function of latitud (row number) [m]*/
double *dr;	/* Distances from center to (1,1) diagonal neigbors [m] */
double *d5x;	/* Distances from center to (1,2) diagonal neigbors [m] */
double *d5y;	/* Distances from center to (2,1) diagonal neigbors [m] */
double *d10x;	/* Distances from center to (1,3) diagonal neigbors [m] */
double *d10y;	/* Distances from center to (3,1) diagonal neigbors [m] */
double *d13x;	/* Distances from center to (2,3) diagonal neigbors [m] */
double *d13y;	/* Distances from center to (3,2) diagonal neigbors [m] */
double *d17x;	/* Distances from center to (1,4) diagonal neigbors [m] */
double *d17y;	/* Distances from center to (4,1) diagonal neigbors [m] */
double *d25x;	/* Distances from center to (3,4) diagonal neigbors [m] */
double *d25y;	/* Distances from center to (4,3) diagonal neigbors [m] */
double *d26x;	/* Distances from center to (1,5) diagonal neigbors [m] */
double *d26y;	/* Distances from center to (5,1) diagonal neigbors [m] */
double *d29x;	/* Distances from center to (2,5) diagonal neigbors [m] */
double *d29y;	/* Distances from center to (5,2) diagonal neigbors [m] */
double *d34x;	/* Distances from center to (3,5) diagonal neigbors [m] */
double *d34y;	/* Distances from center to (5,3) diagonal neigbors [m] */
double *d37x;	/* Distances from center to (1,6) diagonal neigbors [m] */
double *d37y;	/* Distances from center to (6,1) diagonal neigbors [m] */
double *d41x;	/* Distances from center to (4,5) diagonal neigbors [m] */
double *d41y;	/* Distances from center to (5,4) diagonal neigbors [m] */
double *d58x;	/* Distances from center to (3,7) diagonal neigbors [m] */
double *d58y;	/* Distances from center to (7,3) diagonal neigbors [m] */
double *d65x;	/* Distances from center to (1,8) diagonal neigbors [m] */
double *d65y;	/* Distances from center to (8,1) diagonal neigbors [m] */
double *d85x;	/* Distances from center to (6,7) diagonal neigbors [m] */
double *d85y;	/* Distances from center to (7,6) diagonal neigbors [m] */
double *d170x;	/* Distances from center to (1,13) diagonal neigbors [m] */
double *d170y;	/* Distances from center to (13,1) diagonal neigbors [m] */

/* ------------------------ GLOBAL VARIABLES END ------------------------ */
