/*
 * COPYRIGHT (c) 1993-2024 GEOWARE
 *
 * ttt3.h
 *
 * PROGRAM:	ttt.h
 * PURPOSE:	Include file for ttt.c
 * AUTHOR:	Paul Wessel, GEOWARE
 * DATE:	June 16, 1993
 * UPDATED:	January 1, 2024
 * VERSION:	3.2.2
 */

#define TTT_YEAR 	"2024"	/* Latest ttt release year */
#define TTT_VER 	"3.2.2"	/* Latest ttt release version */

/*------------No further edits unless code change------------*/
#define _POSIX_SOURCE 1

/* Standard POSIX include files */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include <ctype.h>
#ifndef WIN32
#include <unistd.h>
#endif

/* Special non-POSIX (typically ANSI extensions) are handled in this
 * separate include file generated by a configure script - or if on
 * Windows we set it directly. */

#ifdef WIN32
#include "ttt_arch_ms.h"
#else
#include "ttt3_arch.h"
#endif

#if TTT_SIZE_P == 8
#define TTT_VERSION 	TTT_VER " [64-bit]"	/* ttt version */
#ifdef _WIN64
typedef __int64 TTT_LONG;	/* A signed 8-byte integer under Windows 64-bit compilation */
#define TTT_LL "ll"
#else
typedef long TTT_LONG;		/* A signed 8 byte integer under OSX/Linux/UNix 64-bit compilation */
#define TTT_LL "l"
#endif
#define LAND		LONG_MAX	/* 9223372036854775807 (64-bit) */
#define USED		(LONG_MAX - 1)	/* 9223372036854775806 (64-bit) */
#define OCEAN		(LONG_MAX - 2)	/* 9223372036854775805 (64-bit) */
#else	/* TTT_SIZE_P == 4 */
#define TTT_VERSION 	TTT_VER " [32-bit]"	/* ttt version */
typedef int TTT_LONG;		/* 4 bytes */
#define TTT_LL ""	/* No modifier needed */
#define LAND		INT_MAX		/* 2147483647 (32-bit) */
#define USED		(INT_MAX - 1)	/* 2147483646 (32-bit) */
#define OCEAN		(INT_MAX - 2)	/* 2147483645 (32-bit) */
#endif

#define N_PAD		5L	/* # of auxillary rows/columns */
#define N_CALC		64	/* No of nodes to calculate itt's to */
#define M_ACCESS	92	/* No of neighboring nodes accessed */
#define	RADIUS		5.0	/* Search radius in degrees for epicenter */
#define DEGREE_TO_METER	(2.0 * M_PI * 6371007.181 / 360.0)	/* Radius of sphere with same surface area */
#define G_E		9.7803267715	/* Three terms used for normal grav equation */
#define G_C1		0.0052790414
#define G_C2		0.0000232718
#define T_UNIT		0.0002		/* Integer unit of time in seconds (currently 0.2 msec) for a max tt of ~119 hours */
#define	UNIT_TO_HOUR 	(T_UNIT / 3600.0)	/* Convert internal timing to hours */
#define LBIT(no)	((unsigned int)(1 << (no)))
#define MBIT(no)	((unsigned int)(1 << ((no)-32)))
#define HBIT(no)	((unsigned int)(1 << ((no)-64)))
#define CHUNK		64
#define IJ(i,j,nx,pad) (((j)+(pad))*(nx)+(i)+(pad))

#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
#ifndef MIN
#define MIN(x, y) (((x) < (y)) ? (x) : (y))     /* min and max value macros */
#endif
#ifndef MAX
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#endif
#ifndef M_PI
#define M_PI	3.14159265358979323846
#endif
#define D2R (M_PI / 180.0)		/* Degrees to radians and back again */
#define R2D (180.0 / M_PI)
#define CONV_LIMIT	1.0e-8		/* "close to zero" limit */
#define ESRI_NAN	-999999.0	/* Used in ESRI flt files */

/* Macros for byte-order swapping 2- and 4-byte values (From John M. Kuhn, NOAA) */

#define TTT_swab2(data) ((((data) & 255) << 8) | ((unsigned short) (data) >> 8))
#define TTT_swab4(data) \
	(((data) << 24) | (((data) << 8) & 16711680) | \
	(((data) >> 8) & 65280) | ((unsigned int)(data) >> 24))

/* The next three functions have leading underscores on Windows.
 * We define them here and they will be picked up below */

#ifdef WIN32
#define hypot(x,y) _hypot(x,y)
#define isnan(x) _isnan(x)
#define tzset _tzset
#define R_OK 04
extern int _access (const char *path, int mode);
#define access(path, mode) _access(path, mode)
#endif

/* Need hypot(x,y) = sqrt (x^2 + y^2); */

#if defined(hypot)
/* Macro already takes care of hypot - probably from WIN32 */
#elif HAVE_HYPOT == 0	/* No hypot function available on this platform, use ours */
#define hypot(x,y) TTT_hypot(x,y)
extern double TTT_hypot(double x, double y);
#else		/* it exists in the C library */
extern double hypot(double x, double y);
#endif

/* Need nearest integer */

#if HAVE_RINT == 0
#define rint(x) (floor((x)+0.5))
#else
extern double rint(double x);
#endif
#if HAVE_IRINT == 0
#define irint(x) ((int)rint(x))
#else
extern int irint(double x);
#endif

/* Need to recognize NaNs */

#if defined(isnanf)
#define TTT_is_fnan(x) isnanf((x))
#elif defined(isnan)
#define TTT_is_fnan(x) isnan((double)(x))
#elif HAVE_ISNANF == 1
#define TTT_is_fnan(x) isnanf(x)
extern int isnanf(float x);
#elif HAVE_ISNAN == 1
#define TTT_is_fnan(x) isnan((double)(x))
#elif HAVE_ISNAND == 1
#define TTT_is_fnan(x) isnand((double)(x))
#else
#define TTT_is_fnan(x) ((x) != (x))
#endif

#if defined(isnand)
#define TTT_is_dnan(x) isnand((x))
#elif defined(isnan)
#define TTT_is_dnan(x) isnan((x))
#elif HAVE_ISNAND == 1
#define TTT_is_dnan(x) isnand(x)
extern int isnand(double x);
#elif HAVE_ISNAN == 1
#define TTT_is_dnan(x) isnan(x)
extern int isnan(double x);
#else
#define TTT_is_dnan(x) ((x) != (x))
#endif

/* Creating NaN values */

#ifdef INTEL	/* Intel/AMD chips typically use this structure */
#define TTT_make_NaN(x) (((unsigned int *) &x)[0] = 0xffffffff)
#else		/* Byte-swapped on RISC machines */
#define TTT_make_NaN(x) (((unsigned int *) &x)[0] = 0x7fffffff)
#endif

#define ttt_x_to_i(x,x0,dx,off,nx) (irint(((((x) - (x0)) / (dx)) - (off))))
#define ttt_y_to_j(y,y0,dy,off,ny) ((ny) - 1 - irint(((((y) - (y0)) / (dy)) - (off))))
#define ttt_i_to_x(i,x0,x1,dx,off,nx) (((i) == ((nx)-1)) ? (x1) - (off) * (dx) : (x0) + ((i) + (off)) * (dx))
#define ttt_j_to_y(j,y0,y1,dy,off,ny) (((j) == ((ny)-1)) ? (y0) + (off) * (dy) : (y1) - ((j) + (off)) * (dy))

typedef short BOOLEAN;

/* Data structure definitions */

/* Reproduce GMT grid header to use in TTT */

#define TTT_IS_GMT_FLOAT	0
#define TTT_IS_GMT_SHORT	1
#define TTT_IS_GRIDFLOAT	2
#define TTT_IS_ESRIASCII	3

#define GRD_COMMAND_LEN	320
#define GRD_REMARK_LEN	160
#define GRD_TITLE_LEN	 80
#define GRD_UNIT_LEN	 80
#define GRD_HEADER_SIZE	892

#define GMT_GRIDLINE_REG	0
#define GMT_PIXEL_REG		1
#define XLO 0
#define XHI 1
#define YLO 2
#define YHI 3
#define TTT_X	0
#define TTT_Y	1

struct GRD_HEADER {	/* From public GMT documentation */
/* Do not change the first three items. They are copied verbatim to the native grid header */
	int nx;				/* Number of columns */
	int ny;				/* Number of rows */
	int registration;		/* 0 for node grids, 1 for pixel grids */
/* This section is flexible. It is not copied to any grid header */
	double xy_off;			/* 0.0 (node_offset == 0) or 0.5 ( == 1) */
	double nan_value;		/* Missing value as stored in grid file */
	int periodic;			/* 1 if 360-degree periodicity */
	int wrap_s;			/* 1 if periodic and S pole */
	int wrap_n;			/* 1 if periodic and N pole */
/* The following elements should not be changed. They are copied verbatim to the native grid header */
	double wesn[4];			/* Min/max x and y coordinates */
	double z_min;			/* Minimum z value */
	double z_max;			/* Maximum z value */
	double inc[2];			/* x and y increment */
	double z_scale_factor;		/* grd values must be multiplied by this */
	double z_add_offset;		/* After scaling, add this */
	char x_units[GRD_UNIT_LEN];	/* units in x-direction */
	char y_units[GRD_UNIT_LEN];	/* units in y-direction */
	char z_units[GRD_UNIT_LEN];	/* grid value units */
	char title[GRD_TITLE_LEN];	/* name of data set */
	char command[GRD_COMMAND_LEN];	/* name of generating command */
	char remark[GRD_REMARK_LEN];	/* comments re this data set */
};

struct TTT_INFO {
	TTT_LONG tt, ij;
	struct TTT_INFO *l, *r;
};

/* ----------------------- GLOBAL VARIABLES BEGIN ----------------------- */

char *TTT_DIR;		/* Directory with .i2 files */
char *TTT_ext[5] = {"b", "i2", "hdr", "asc", "flt"};
char *TTT_wmode[5] = {"wb", "wb", "w", "w", "wb"};
char *TTT_rmode[5] = {"rb", "rb", "r", "r", "rb"};

unsigned int low_use_bits[M_ACCESS];	/* Array of bits indicating which nodes k < 32 to use for each node */
unsigned int med_use_bits[M_ACCESS];	/* Array of bits indicating which nodes 32 <= k < 64 to use for each node */
unsigned int high_use_bits[M_ACCESS];	/* Array of bits indicating which nodes 64 <= k < 92 to use for each node */

/* All the following distances are normalized by the number of x-increments required */

double dy;	/* Constant distance (no array needed) between y-nodes [m(eters)] */
double *dx;	/* Distances between x-nodes as a function of latitud (row number) [m]*/
double *dr;	/* Distances from center to (1,1) diagonal neigbors [m] */
double *d5x;	/* Distances from center to (1,2) diagonal neigbors [m] */
double *d5y;	/* Distances from center to (2,1) diagonal neigbors [m] */
double *d10x;	/* Distances from center to (1,3) diagonal neigbors [m] */
double *d10y;	/* Distances from center to (3,1) diagonal neigbors [m] */
double *d13x;	/* Distances from center to (2,3) diagonal neigbors [m] */
double *d13y;	/* Distances from center to (3,2) diagonal neigbors [m] */
double *d17x;	/* Distances from center to (1,4) diagonal neigbors [m] */
double *d17y;	/* Distances from center to (4,1) diagonal neigbors [m] */
double *d25x;	/* Distances from center to (3,4) diagonal neigbors [m] */
double *d25y;	/* Distances from center to (4,3) diagonal neigbors [m] */
double *d26x;	/* Distances from center to (1,5) diagonal neigbors [m] */
double *d26y;	/* Distances from center to (5,1) diagonal neigbors [m] */
double *d29x;	/* Distances from center to (2,5) diagonal neigbors [m] */
double *d29y;	/* Distances from center to (5,2) diagonal neigbors [m] */

/* ------------------------ GLOBAL VARIABLES END ------------------------ */
