 
/* configured options and settings for GMT */
#define GMT_PACKAGE_VERSION_MAJOR @GMT_PACKAGE_VERSION_MAJOR@
#define GMT_PACKAGE_VERSION_MINOR @GMT_PACKAGE_VERSION_MINOR@
#define GMT_PACKAGE_VERSION_PATCH @GMT_PACKAGE_VERSION_PATCH@

#define GMT_PACKAGE_VERSION "@GMT_PACKAGE_VERSION@"
#define GMT_SVN_REVISION "@SVN_VERSION@"
#define GMT_PACKAGE_VERSION_WITH_SVN_REVISION "@GMT_PACKAGE_VERSION_WITH_SVN_REVISION@"

#define GMT_VERSION_STRING "@GMT_VERSION_STRING@"
#define GMT_LONG_VERSION_STRING "@GMT_LONG_VERSION_STRING@"

/* path to shared files */
#define GMT_SHARE_PATH "@GMT_SHARE_PATH@"

