#!/bin/sh
#-----------------------------------------------------------------------------
#	 $Id: webman.sh,v 1.12 2003-04-01 07:07:39 pwessel Exp $
#
#	webman.csh - Automatic generation of the GMT web manual pages
#
#	Author:	Paul Wessel
#	Date:	17-SEP-1999
#	Version: 1.1 Bourne shell
#
#	Uses the man2html program + alot of sed and awk...
#	Assumes a cvs update has occured so files are fresh.
#
#	Must be run from the main GMT directory after man pages have
#	been made.
#
#	On HP (raptor) we must do an extra sed substitution since some
#	blank lines comes through as lines with ?9 at the end or line
#	(? is some unknown character).  This sed line is added to the
#	webman1.sed file
#-----------------------------------------------------------------------------

if [ $#argv = 1 ]; then	# If -s is given we run silently with defaults
	gush=0
else			# else we make alot of noise
	gush=1
fi

mkdir -p www/gmt/doc/html

# First make a list of all the GMT programs, including pslib (since it has a man page) and the GMT script

grep -v '^#' guru/GMT_programs.lis > programs.lis
echo GMT >> programs.lis
echo pslib >> programs.lis

# Now make sed script (actually 3, since sed seems to have trouble with long sed scripts...)

awk '{printf "s%%>%s<%%><a href=%c%s.html%c>%s</a><%%g\n", $1, 34, $1, 34, $1}' programs.lis > webman1.sed
awk '{printf "s%%%s,%%<a href=%c%s.html%c>%s</a>,%%g\n", $1, 34, $1, 34, $1}' programs.lis > webman2.sed
awk '{printf "s%%%s$%%<a href=%c%s.html%c>%s</a>%%g\n", $1, 34, $1, 34, $1}' programs.lis > webman3.sed

# Fix for man on HP that gives 9s in output
echo 's/^.9$//g' >> webman1.sed

# Ok, go to source directory and make html files
# the -pgsize 5000 is needed since nroff does not do pages anymore?
for prog in `cat programs.lis`; do
	if [ $gush = 1 ]; then
		echo "Making ${prog}.html"
	fi
	grep -v ${prog} webman1.sed > this1.sed
	grep -v ${prog} webman2.sed > this2.sed
	grep -v ${prog} webman3.sed > this3.sed
	nroff -man man/manl/${prog}.l | $MAN2HTML -topm 4 -pgsize 5000 | sed -f this1.sed | sed -f this2.sed | sed -f this3.sed > www/gmt/doc/html/${prog}.html
	echo '<body bgcolor="#ffffff">' >> www/gmt/doc/html/${prog}.html
done

# Ok, then do the supplemental packages

# Gurus who have their own supplemental packages can have them processed too by
# defining an environmental parameter MY_GMT_SUPPL which contains a list of these
# supplements.  THey must all be in src of course

MY_SUPPL=${MY_GMT_SUPPL:-""}
cd src
for package in dbase imgsrc meca mgg misc segyprogs spotter x2sys x_system $MY_SUPPL; do
	for f in $package/*.man; do
		prog=`basename $f .man`
		if [ $gush = 1 ]; then
			echo "Making ${prog}.html"
		fi
		nroff -man $f | $MAN2HTML -topm 4 | sed -f ../webman1.sed | sed -f ../webman2.sed | sed -f ../webman3.sed > $package/${prog}.html
		echo '<body bgcolor="#ffffff">' >> $package/${prog}.html
	done
done
cd ..

#-----------------------------------------------------------------
#	Generate the main GMT Manual page directory
#-----------------------------------------------------------------

cat << EOF > www/gmt/gmt_man.html
<html>
<!-- gmt_man.html - Automatically generated by webman.sh  -->
<title>GMT Online Man Pages</title>
<body bgcolor="#ffffff">
<p><center><img src="images/gmt_bar.gif" alt="---------------------------------"></center></P>
<center><h1>GMT Online Man Pages</h1></center><p>
These man pages are html-versions of the Unix man pages for GMT.  They
are grouped by function. For an alphabetical order, click <a href="#anchor_alpha">here</a>.
<h2><a NAME="anchor_theme">Thematic listing of GMT Unix man pages</h2>
<hr>
<h3>GMT WRAPPER:</h3>
<ul>
<li><a href="doc/html/GMT.html"> GMT</a> A Wrapper for GMT programs</li>
</ul>
<h3>FILTERING OF 1-D AND 2-D DATA:</h3>
<ul>
<li><a href="doc/html/blockmean.html"> blockmean</a> L2 (x,y,z) data filter/decimator</li>
<li><a href="doc/html/blockmedian.html"> blockmedian</a> L1 (x,y,z) data filter/decimator</li>
<li><a href="doc/html/blockmode.html"> blockmode</a> Mode-estimating (x,y,z) data filter/decimator</li>
<li><a href="doc/html/filter1d.html"> filter1d</a> Filter 1-D data (time series)</li>
<li><a href="doc/html/grdfilter.html"> grdfilter</a> Filter 2-D data in space domain</li>
</ul>
<h3>PLOTTING OF 1-D and 2-D DATA:</h3>
<ul>
<li><a href="doc/html/grdcontour.html"> grdcontour</a> Contouring of 2-D gridded data</li>
<li><a href="doc/html/grdimage.html"> grdimage</a> Produce images from 2-D gridded datar</li>
<li><a href="doc/html/grdvector.html"> grdvector</a> Plot vector fields from 2-D gridded data</li>
<li><a href="doc/html/grdview.html"> grdview</a> 3-D perspective imaging of 2-D gridded data</li>
<li><a href="doc/html/psbasemap.html"> psbasemap</a> Create a basemap frame</li>
<li><a href="doc/html/psclip.html"> psclip</a> Use polygon files as clipping paths</li>
<li><a href="doc/html/pscoast.html"> pscoast</a> Plot coastlines, filled continents, rivers, and political borders</li>
<li><a href="doc/html/pscontour.html"> pscontour</a> Direct contouring or imaging of xyz-data by triangulation</li>
<li><a href="doc/html/pshistogram.html"> pshistogram</a> Plot a histogram</li>
<li><a href="doc/html/psimage.html"> psimage</a> Plot Sun rasterfiles on a map</li>
<li><a href="doc/html/pslegend.html"> pslegend</a> Plot legend on a map</li>
<li><a href="doc/html/psmask.html"> psmask</a> Create overlay to mask specified regions of a map</li>
<li><a href="doc/html/psrose.html"> psrose</a> Plot sector or rose diagrams</li>
<li><a href="doc/html/psscale.html"> psscale</a> Plot grayscale or colorscale</li>
<li><a href="doc/html/pstext.html"> pstext</a> Plot textstrings</li>
<li><a href="doc/html/pswiggle.html"> pswiggle</a> Draw anomalies along track</li>
<li><a href="doc/html/psxy.html"> psxy</a> Plot symbols, polygons, and lines in 2-D</li>
<li><a href="doc/html/psxyz.html"> psxyz</a> Plot symbols, polygons, and lines in 3-D</li>
</ul>
<h3>GRIDDING OF (X,Y,Z) DATA:</h3>
<ul>
<li><a href="doc/html/nearneighbor.html"> nearneighbor</a> Nearest-neighbor gridding scheme</li>
<li><a href="doc/html/surface.html"> surface</a> Continuous curvature gridding algorithm</li>
<li><a href="doc/html/triangulate.html"> triangulate</a> Perform optimal Delauney triangulation on xyz data</li>
</ul>
<h3>SAMPLING OF 1-D AND 2-D DATA:</h3>
<ul>
<li><a href="doc/html/grdsample.html"> grdsample</a> Resample a 2-D gridded data onto new grid</li>
<li><a href="doc/html/grdtrack.html"> grdtrack</a> Sampling of 2-D data along 1-D track</li>
<li><a href="doc/html/sample1d.html"> sample1d</a> Resampling of 1-D data</li>
</ul>
<h3>PROJECTION AND MAP-TRANSFORMATION:</h3>
<ul>
<li><a href="doc/html/grdproject.html"> grdproject</a> Project gridded data onto new coordinate system</li>
<li><a href="doc/html/mapproject.html"> mapproject</a> Transformation of coordinate systems</li>
<li><a href="doc/html/project.html"> project</a> Project data onto lines/great circles</li>
</ul>
<h3>INFORMATION:</h3>
<ul>
<li><a href="doc/html/gmtdefaults.html"> gmtdefaults</a> List the current default settings</li>
<li><a href="doc/html/gmtset.html"> gmtset</a> Edit parameters in the .gmtdefaults file</li>
<li><a href="doc/html/grdinfo.html"> grdinfo</a> Get information about grd files</li>
<li><a href="doc/html/minmax.html"> minmax</a> Report extreme values in table datafiles</li>
</ul>
<h3>CONVERT OR EXTRACT SUBSETS OF DATA:</h3>
<ul>
<li><a href="doc/html/gmt2rgb.html"> gmtconvert</a> Convert Sun raster or grdfile to red, green, blue component grids</li>
<li><a href="doc/html/gmtconvert.html"> gmtconvert</a> Convert table data from one format to another</li>
<li><a href="doc/html/gmtmath.html"> gmtmath</a> Reverse Polish calculator for table data</li>
<li><a href="doc/html/gmtselect.html"> gmtselect</a> Select table subsets based on multiple spatial criteria</li>
<li><a href="doc/html/grd2xyz.html"> grd2xyz</a> Convert 2-D gridded data to table</li>
<li><a href="doc/html/grdcut.html"> grdcut</a> Cut a sub-region from a grd file</li>
<li><a href="doc/html/grdpaste.html"> grdpaste</a> Paste together grdfiles along common edge</li>
<li><a href="doc/html/grdreformat.html"> grdreformat</a> Convert from one grdformat to another</li>
<li><a href="doc/html/splitxyz.html"> splitxyz</a> Split xyz files into several segments</li>
<li><a href="doc/html/xyz2grd.html"> xyz2grd</a> Convert table to 2-D grd file</li>
</ul>
<h3>MISCELLANEOUS:</h3>
<ul>
<li><a href="doc/html/makecpt.html"> makecpt</a> Create GMT color palette tables</li>
<li><a href="doc/html/spectrum1d.html"> spectrum1d</a> Compute spectral estimates from time-series</li>
<li><a href="doc/html/triangulate.html"> triangulate</a> Perform optimal Delauney triangulation on xyz data</li>
</ul>
<h3>DETERMINE TRENDS IN 1-D AND 2-D DATA:</h3>
<ul>
<li><a href="doc/html/fitcircle.html"> fitcircle</a> Finds best-fitting great or small circles</li>
<li><a href="doc/html/grdtrend.html"> grdtrend</a> Fits polynomial trends to grdfiles (z = f(x,y))</li>
<li><a href="doc/html/trend1d.html"> trend1d</a> Fits polynomial or Fourier trends to y = f(x) series</li>
<li><a href="doc/html/trend2d.html"> trend2d</a> Fits polynomial trends to z = f(x,y) series</li>
</ul>
<h3>OTHER OPERATIONS ON 2-D GRIDS:</h3>
<ul>
<li><a href="doc/html/grd2cpt.html"> grd2cpt</a> Make color palette table from grdfile</li>
<li><a href="doc/html/grdblend.html"> grdclip</a> Blend several gridded data sets into one</li>
<li><a href="doc/html/grdclip.html"> grdclip</a> Limit the z-range in gridded data sets</li>
<li><a href="doc/html/grdedit.html"> grdedit</a> Modify grd header information</li>
<li><a href="doc/html/grdfft.html"> grdfft</a> Operate on grdfiles in frequency domain</li>
<li><a href="doc/html/grdgradient.html"> grdgradient</a> Compute directional gradient from grdfiles</li>
<li><a href="doc/html/grdhisteq.html"> grdhisteq</a> Histogram equalization for grdfiles</li>
<li><a href="doc/html/grdlandmask.html"> grdlandmask</a> Creates mask grdfile from coastline database</li>
<li><a href="doc/html/grdmask.html"> grdmask</a> Set nodes outside a clip path to a constant</li>
<li><a href="doc/html/grdmath.html"> grdmath</a> Reverse Polish calculator for grdfiles</li>
<li><a href="doc/html/grdvolume.html"> grdvolume</a> Calculating volume under a surface within a contour</li>
</ul>
<h3>POSTSCRIPT LIBRARY FUNCTION CALLS (for developers):</h3>
<ul>
<li><a href="doc/html/pslib.html"> pslib</a> Reference manual for libpsl.a</li>
</ul>
<hr>
<h2><A NAME="anchor_alpha">Alphabetical listing of GMT Unix man pages</h2>
<OL>
EOF
# Exclude pslib since it is not a program
grep -v pslib programs.lis | awk '{printf "<li><a href=%cdoc/html/%s.html%c> %s</a></li>\n", 34, $1, 34, $1}' >> www/gmt/gmt_man.html
cat << EOF >> www/gmt/gmt_man.html
</OL>
<hr>
For a thematic listing of GMT man pages, click <a href="#anchor_theme">here</a>.
<p><center><img src="images/gmt_bar.gif" ALT="---------------------------------"></center></P>
<a href="gmt_services.html">
<img src="images/gmt_back.gif" ALT="RETURN">
Return to GMT Online Services page.
</a>
</html>
EOF

#-----------------------------------------------------------------
#	Generate the supplemental GMT Manual page directory
#-----------------------------------------------------------------

cat << EOF > www/gmt/gmt_suppl.html
<html>
<!-- gmt_suppl.html - Automatically generated by webman.sh  -->
<title>GMT Supplemental Online Man Pages</title>
<body bgcolor="#ffffff">
<p><center><img src="images/gmt_bar.gif" alt="---------------------------------"></center></P>
<center><h1>GMT Supplemental Online Man Pages</h1></center><p>
These man pages are html-versions of the Unix man pages for the GMT
supplemental programs, grouped by package.  Note that only the
packages actually installed on your system will be accessible.
<hr>
<h3>The DBASE package</h3>
<ul>
<li><a href="doc/html/grdraster.html"> grdraster</a> Extraction of gridfiles from databases</li>
</ul>
<hr>
<h3>The IMGSRC package</h3>
<ul>
<li><a href="doc/html/img2grd.html"> img2grd</a> Front-end Bourne script to img2mercgrd</li>
<li><a href="doc/html/img2mercgrd.html"> img2mercgrd</a> Extracting data from Sandwell/Smith altimetry solutions</li>
</ul>
<hr>
<h3>The MECA package</h3>
<ul>
<li><a href="doc/html/pscoupe.html"> pscoupe</a> Plot seismic moment tensor and/or double couples on a cross-section</li>
<li><a href="doc/html/psmeca.html"> psmeca</a> Plot seismic moment tensor and/or double couples on maps</li>
<li><a href="doc/html/pspolar.html"> pspolar</a> Plot polarities on the lower half-sphere</li>
<li><a href="doc/html/psvelo.html"> psvelo</a> Plot velocity ellipses, strain crosses, or strain wedges on maps</li>
</ul>
<hr>
<h3>The MGG package</h3>
<ul>
<li><a href="doc/html/binlegs.html"> binlegs</a> Maintain shiptrack index files database</li>
<li><a href="doc/html/dat2gmt.html"> dat2gmt</a> Convert ASCII listing to .gmt file</li>
<li><a href="doc/html/gmt2bin.html"> gmt2bin</a> Create bin-index files from .gmt files</li>
<li><a href="doc/html/gmt2dat.html"> gmt2dat</a> Write .gmt file as ASCII listing</li>
<li><a href="doc/html/gmtinfo.html"> gmtinfo</a> Report statistics of .gmt files</li>
<li><a href="doc/html/gmtlegs.html"> gmtlegs</a> Find all ship tracks in given area</li>
<li><a href="doc/html/gmtlist.html"> gmtlist</a> Extract data from .gmt files</li>
<li><a href="doc/html/gmtpath.html"> gmtpath</a> Find actual path to .gmt files</li>
<li><a href="doc/html/gmttrack.html"> gmttrack</a> Plot ship tracks on maps</li>
<li><a href="doc/html/mgd77togmt.html"> mgd77togmt</a> Convert MGD-77 files to .gmt format</li>
</ul>
<hr>
<h3>The MISC package</h3>
<ul>
<!-- <li><a href="doc/html/gmtdigitize.html"> gmtdigitize</a> Digitize features using a digitizer</li> -->
<li><a href="doc/html/makepattern.html"> makepattern</a> Make GMT color pattern from b/w pattern</li>
<li><a href="doc/html/psmegaplot.html"> psmegaplot</a> Make poster-size plot using tiling</li>
</ul>
<hr>
<h3>The SEGYPROGS package</h3>
<ul>
<li><a href="doc/html/pssegy.html"> pssegy</a> Plot SEGY seismic data files in 2-D</li>
<li><a href="doc/html/pssegyz.html"> pssegyz</a> Plot SEGY seismic data files in 3-D</li>
</ul>
<hr>
<h3>The SPOTTER package</h3>
<ul>
<li><a href="doc/html/backtracker.html"> backtracker</a> Forward and backward flowlines or hotspot tracks</li>
<li><a href="doc/html/hotspotter.html"> hotspotter</a> Make CVA grids by convolving flowlines and seamount shapes</li>
<li><a href="doc/html/originator.html"> originator</a> Associate seamounts with hotspot point sources</li>
<li><a href="doc/html/rotconverter.html"> rotconverter</a> Manipulate finite and stage rotations</li>
</ul>
<hr>
<h3>The X2SYS package</h3>
<ul>
<li><a href="doc/html/x2sys_cross.html"> x2sys_cross</a> Generic track intersection (Crossover) detector</li>
<li><a href="doc/html/x2sys_datalist.html"> x2sys_datalist</a> Generic data extractor for ASCII and binary track data</li>
</ul>
<hr>
<h3>The X_SYSTEM package</h3>
<ul>
<li><a href="doc/html/x_system.html"> x_system</a> MGG-specific track intersection (Crossover) System Overview</li>
<li><a href="doc/html/x_edit.html"> x_edit</a> Convert between ascii and binary crossover correction tables</li>
<li><a href="doc/html/x_init.html"> x_init</a> Initialize a new crossover data base</li>
<li><a href="doc/html/x_list.html"> x_list</a> Extract crossover data from data base</li>
<li><a href="doc/html/x_over.html"> x_over</a> Calculate crossovers between two MGG cruise files in *.gmt format</li>
<li><a href="doc/html/x_remove.html"> x_remove</a> Remove crossover information from data base</li>
<li><a href="doc/html/x_report.html"> x_report</a> Summarize crossover statistics from data base</li>
<li><a href="doc/html/x_setup.html"> x_setup</a> Determine which cruises need to be compared to current files</li>
<li><a href="doc/html/x_solve_dc_drift.html"> x_solve_dc_drift</a> Find best-fitting offset and drift-rates</li>
<li><a href="doc/html/x_update.html"> x_update</a> Update data base with new crossover information</li>
</ul>
<hr>
<h3>The XGRID package</h3>
<ul>
<li>xgridedit  A GUI editor of gridfiles</li>
</ul>
<p>
<a href="gmt_services.html">
<img src="images/gmt_back.gif" alt="RETURN">
Return to GMT Online Services page.
</a>
</html>
EOF

# Clean up

rm -f webman?.sed this?.sed programs.lis lis
