"abyss       : Black/dark blue to lightblue for bathymetry [R=-8000/0, C=RGB]",
"acton       : Perceptually uniform sequential colormap, by Fabio Crameri [C=RGB]",
"bamako      : Perceptually uniform, low-lightness gradient colormap by Fabio Crameri [C=RGB]",
"bathy       : Like abyss but via aquamarine at mid-depths [R=-8000/0, C=RGB]",
"batlow      : Perceptually uniform sequential \'rainbow\' colormap by, Fabio Crameri [C=RGB]",
"berlin      : Perceptually uniform bimodal colormap, dark, by Fabio Crameri [S,C=RGB]",
"bilbao      : Perceptually uniform colormap by Fabio Crameri [C=RGB]",
"broc        : Perceptually uniform bimodal colormap, light, by Fabio Crameri [S,C=RGB]",
"buda        : Perceptually uniform, low-lightness gradient colormap, by Fabio Crameri [C=RGB]",
"categorical : Color table particularly suitable for categorical data [vRGB]",
"cool        : Linear change from blue to magenta [C=RGB]",
"copper      : Dark to light copper brown [C=RGB]",
"cork        : Perceptually uniform bimodal colormap, light, by Fabio Crameri [S,C=RGB]",
"cubhelix    : Intensity colormap via cube helix by Dave Green [C=RGB]",
"cyclic      : Cyclic colormap, spans 360 degrees of hue [C=HSV]",
"davos       : Perceptually uniform colormap by Fabio Crameri [C=RGB]",
"dem1        : Digital Elevation Model (DEM) scale by Thomas Dewez [R=0/800, C=RGB]",
"dem2        : Digital Elevation Model (DEM) scale by Dewez/Wessel [R=0/4900, C=RGB]",
"dem3        : Digital Elevation Model (DEM) scale by Paul Wessel [R=0/6000, C=RGB]",
"dem4        : Digital Elevation Model (DEM) scale for Wikipedia figures [R=0/1500, C=RGB]",
"devon       : Perceptually uniform sequential colormap, by Fabio Crameri [C=RGB]",
"drywet      : Goes from dry to wet colors [C=RGB]",
"earth       : Colors for global bathymetry/topography relief [R=-11000/9000, H, C=RGB]",
"elevation   : Washed-out colors for topography [R=0/7000, C=RGB]",
"etopo1      : Colormap used in the ETOPO1 global relief map [R=-11000/8500, H, C=RGB]",
"gebco       : Colors for GEBCO bathymetric charts [R=-7000/0, C=RGB]",
"geo         : Colors for global bathymetry/topography relief [R=-8000/8000, H, C=RGB]",
"globe       : Colors for global bathymetry/topography relief [R=-10000/10000, H, C=RGB]",
"gray        : Gray linear ramp from black to white [C=RGB]",
"grayC       : Perceptually uniform \'gray\' colormap, by Fabio Crameri [C=RGB]",
"hawaii      : Perceptually uniform sequential colormap, by Fabio Crameri [C=RGB]",
"haxby       : Bill Haxby's color scheme for geoid & gravity [C=RGB]",
"hot         : Black through red and yellow to white [C=RGB]",
"ibcso       : The IBCSO bathymetry colors [R=-12000/0, C=RGB]",
"imola       : Perceptually uniform, low-lightness gradient colormap, by Fabio Crameri [C=RGB]",
"inferno     : New colormap Option B from matplotlib [C=RGB]",
"jet         : Dark to light blue, white, yellow and red [C=RGB]",
"lajolla     : Perceptually uniform colormap, without black or white, by Fabio Crameri [C=RGB]",
"lapaz       : Perceptually uniform \'rainbow\' colormap, by Fabio Crameri [C=RGB]",
"lisbon      : Perceptually uniform bimodal colormap, dark, by Fabio Crameri [S,C=RGB]",
"mag         : Colors for magnetic anomaly maps [C=RGB]",
"magma       : New colormap Option A from matplotlib [C=RGB]",
"nighttime   : Colors for DMSP-OLS Nighttime Lights Time Series [C=HSV]",
"no_green    : For those who hate green [S, C=RGB]",
"nuuk        : Perceptually uniform, low-lightness gradient colormap, by Fabio Crameri [C=RGB]",
"ocean       : White-green-blue bathymetry scale [R=-8000/0, C=RGB]",
"oleron      : Perceptually uniform topography colormap, by Fabio Crameri [H,C=RGB]",
"oslo        : Perceptually uniform, black & white limits, by Fabio Crameri [C=RGB]",
"paired      : Qualitative color map with 6 pairs of colors [C=RGB]",
"panoply     : Default colormap of Panoply [C=RGB]",
"plasma      : New colormap Option C from matplotlib [C=RGB]",
"polar       : Blue via white to red [S, C=RGB]",
"rainbow     : Rainbow: magenta-blue-cyan-green-yellow-red [C=HSV]",
"red2green   : Polar scale from red to green via white [S, C=RGB]",
"relief      : Wessel/Martinez colors for topography [R=-8000/+8000, H, C=RGB]",
"roma        : Perceptually uniform \'seis\' colormap, by Fabio Crameri [C=RGB]",
"seafloor    : Purple-blue-white bathymetry scale [R=-6000/0, C=RGB]",
"sealand     : Smith bathymetry/topography scale [R=-6000/+3000, H, C=HSV]",
"seis        : R-O-Y-G-B seismic tomography colors [C=RGB]",
"split       : Like polar, but via black instead of white [S, C=RGB]",
"srtm        : Like dem2, but with blue for oceans [H, C=RGB]",
"terra       : Colors for global bathymetry/topography relief [R=-7000/7000, H, C=RGB]",
"tofino      : Perceptually uniform bimodal colormap, dark, by Fabio Crameri [S,C=RGB]",
"tokyo       : Perceptually uniform colormap without black or white, by Fabio Crameri [C=RGB]",
"topo        : Sandwell/Anderson colors for topography [R=-7000/+7000, H, C=HSV]",
"turku       : Perceptually uniform colormap by Fabio Crameri [C=RGB]",
"turbo       : Google's Improved Rainbow Colormap for Visualization [C=RGB]",
"vik         : Perceptually uniform bimodal colormap, light, by Fabio Crameri [S,C=RGB]",
"viridis     : New colormap Option D from matplotlib [C=RGB]",
"world       : Colors for global bathymetry/topography relief [R=-7000/7000, H, C=RGB]",
"wysiwyg     : 20 well-separated RGB colors [C=RGB]"
