	{"earthtide", "earthtide", "geodesy", "Compute grids or time-series of solid Earth tides", ">D},GG),>DL,>DS"},
	{"gpsgridder", "gpsgridder", "geodesy", "Interpolate GPS strains using Green's functions for elastic deformation", "<D{,ND(,TG(,CD)=f,GG}"},
	{"velo", "psvelo", "geodesy", "Plot velocity vectors, crosses, and wedges", "<D{,>X}"},
	{"gshhg", "gshhg", "gshhg", "Extract data tables from binary GSHHG or WDBII data files", ">D}"},
	{"img2grd", "img2grd", "img", "Extract a subset from an img file in Mercator or Geographic format", "<G{,GG}"},
	{"mgd77convert", "mgd77convert", "mgd77", "Convert MGD77 data to other formats", ""},
	{"mgd77header", "mgd77header", "mgd77", "Create MGD77 headers from A77 files", ""},
	{"mgd77info", "mgd77info", "mgd77", "Extract information about MGD77 files", ""},
	{"mgd77list", "mgd77list", "mgd77", "Extract data from MGD77 files", ">D}"},
	{"mgd77magref", "mgd77magref", "mgd77", "Evaluate the IGRF or CM4 magnetic field models", "<D{,>D}"},
	{"mgd77manage", "mgd77manage", "mgd77", "Manage the content of MGD77+ files", ""},
	{"mgd77path", "mgd77path", "mgd77", "Return paths to MGD77 cruises and directories", ">D}"},
	{"mgd77sniffer", "mgd77sniffer", "mgd77", "Along-track quality control of MGD77 cruises", ""},
	{"mgd77track", "mgd77track", "mgd77", "Plot track-lines of MGD77 cruises", ">X}"},
	{"gmtflexure", "gmtflexure", "potential", "Compute flexural deformation of 2-D loads, forces, and bending moments", "ED(,QD(,TD(,>D}"},
	{"gmtgravmag3d", "gmtgravmag3d", "potential", "Compute the gravity/magnetic anomaly of a 3-D body by the method of Okabe", "TD{,FD(,GG),>D}"},
	{"gravfft", "gravfft", "potential", "Spectral calculations of gravity, isostasy, admittance, and coherence for grids", "<G{+,GG},DG(,GDC,GDI"},
	{"grdflexure", "grdflexure", "potential", "Compute flexural deformation of 3-D surfaces for various rheologies", "<G{,GG},LD),TD("},
	{"grdgravmag3d", "grdgravmag3d", "potential", "Computes the gravity effect of one (or two) grids by the method of Okabe", "<G{+,FD(,GG}"},
	{"grdredpol", "grdredpol", "potential", "Compute the Continuous Reduction To the Pole, AKA differential RTP", "<G{,EG(,GG},ZG)"},
	{"grdseamount", "grdseamount", "potential", "Create synthetic seamounts (Gaussian, parabolic, cone or disc, circular or elliptical)", "<T{,GG},TD("},
	{"talwani2d", "talwani2d", "potential", "Compute geopotential anomalies over 2-D bodies by the method of Talwani", "<D{,ND(,>D}"},
	{"talwani3d", "talwani3d", "potential", "Compute geopotential anomalies over 3-D bodies by the method of Talwani", "<D{,ND(,ZG(,G?},GDN"},
	{"segy", "pssegy", "segy", "Plot a SEGY file in 2-D", ">X}"},
	{"segy2grd", "segy2grd", "segy", "Converting SEGY data to a grid", "GG}"},
	{"segyz", "pssegyz", "segy", "Plot a SEGY file in 3-D", ">X}"},
	{"coupe", "pscoupe", "seis", "Plot cross-sections of focal mechanisms", "<D{,>X}"},
	{"meca", "psmeca", "seis", "Plot focal mechanisms", "<D{,>X}"},
	{"polar", "pspolar", "seis", "Plot polarities on the lower hemisphere of the focal sphere", "<D{,>X}"},
	{"sac", "pssac", "seis", "Plot seismograms in SAC format", ">X},RG-"},
	{"backtracker", "backtracker", "spotter", "Generate forward and backward flowlines and hotspot tracks", "<D{,>D},FD("},
	{"gmtpmodeler", "gmtpmodeler", "spotter", "Evaluate a plate motion model at given locations", "<D{,FD(,>D}"},
	{"grdpmodeler", "grdpmodeler", "spotter", "Evaluate a plate motion model on a geographic grid", "<G{,FD(,GG),>DG"},
	{"grdrotater", "grdrotater", "spotter", "Finite rotation reconstruction of geographic grid", "<G{,FD(,GG},TD("},
	{"grdspotter", "grdspotter", "spotter", "Create CVA grid from a gravity or topography grid", "<G{,AG(,DG),LG),GG}"},
	{"hotspotter", "hotspotter", "spotter", "Create CVA grid from seamount locations", "<D{,GG}"},
	{"originater", "originater", "spotter", "Associate seamounts with nearest hotspot point sources", "<D{,FD(=,>D}"},
	{"polespotter", "polespotter", "spotter", "Find stage poles given fracture zones and abyssal hills", "AD(,CD),FD(,GG},LD)"},
	{"rotconverter", "rotconverter", "spotter", "Manipulate total reconstruction and stage rotations", ">D}"},
	{"rotsmoother", "rotsmoother", "spotter", "Get mean rotations and covariance matrices from set of finite rotations", "<D{,>D}"},
	{"x2sys_binlist", "x2sys_binlist", "x2sys", "Create bin index listing from track data files", ">D}"},
	{"x2sys_cross", "x2sys_cross", "x2sys", "Calculate crossovers between track data files", "<D{,>D}"},
	{"x2sys_datalist", "x2sys_datalist", "x2sys", "Extract content of track data files", ">D}"},
	{"x2sys_get", "x2sys_get", "x2sys", "Get track listing from track index database", ">D}"},
	{"x2sys_init", "x2sys_init", "x2sys", "Initialize a new x2sys track database", ""},
	{"x2sys_list", "x2sys_list", "x2sys", "Extract subset from crossover data base", ">D}"},
	{"x2sys_merge", "x2sys_merge", "x2sys", "Merge an updated COEs table (smaller) into the main table (bigger)", ">D}"},
	{"x2sys_put", "x2sys_put", "x2sys", "Update track index database from track bin file", ""},
	{"x2sys_report", "x2sys_report", "x2sys", "Report statistics from crossover data base", ">D}"},
	{"x2sys_solve", "x2sys_solve", "x2sys", "Determine least-squares systematic correction from crossovers", ">D}"},
