	{"AU", "CT", "Australia Capitol Territory"},
	{"AU", "NS", "New South Wales"},
	{"AU", "NT", "Northern Territory"},
	{"AU", "QL", "Queensland"},
	{"AU", "SA", "South Australia"},
	{"AU", "VI", "Victoria"},
	{"AU", "WA", "West Australia"},
	{"AU", "TS", "Tasmania"},
	{"BR", "AC", "Acre"},
	{"BR", "AL", "Alagoas"},
	{"BR", "AP", "Amapa"},
	{"BR", "AM", "Amazonas"},
	{"BR", "BA", "Bahia"},
	{"BR", "CE", "Ceara"},
	{"BR", "DF", "Distrito Federal"},
	{"BR", "RN", "Rio Grande do Norte"},
	{"BR", "RS", "Rio Grande do Sul"},
	{"BR", "ES", "Espirito Santo"},
	{"BR", "GO", "Goias"},
	{"BR", "LZ", "Litigated Zone"},
	{"BR", "MA", "Maranhao"},
	{"BR", "MT", "Mato Grosso"},
	{"BR", "MG", "Minas Gerais"},
	{"BR", "PA", "Para"},
	{"BR", "PB", "Paraiba"},
	{"BR", "PR", "Parana"},
	{"BR", "PE", "Pernambuco"},
	{"BR", "PI", "Piaui"},
	{"BR", "RJ", "Rio de Janeiro"},
	{"BR", "RO", "Rondonia"},
	{"BR", "RR", "Roraima"},
	{"BR", "SC", "Santa Catarina"},
	{"BR", "SP", "Sao Paulo"},
	{"BR", "SE", "Sergipe"},
	{"CA", "AB", "Alberta"},
	{"CA", "BC", "British Columbia"},
	{"CA", "MB", "Manitoba"},
	{"CA", "NB", "New Brunswick"},
	{"CA", "NF", "Newfoundland"},
	{"CA", "NT", "Northwest Territories"},
	{"CA", "NS", "Nova Scotia"},
	{"CA", "ON", "Ontario"},
	{"CA", "PE", "Prince Edward Island"},
	{"CA", "QC", "Quebec"},
	{"CA", "SK", "Saskatchewan"},
	{"CA", "YT", "Yukon Territory"},
	{"US", "AL", "Alabama"},
	{"US", "AK", "Alaska"},
	{"US", "AZ", "Arizona"},
	{"US", "AR", "Arkansas"},
	{"US", "CA", "California"},
	{"US", "CO", "Colorado"},
	{"US", "CT", "Connecticut"},
	{"US", "DE", "Delaware"},
	{"US", "FL", "Florida"},
	{"US", "GA", "Georgia"},
	{"US", "HI", "Hawaii"},
	{"US", "ID", "Idaho"},
	{"US", "IL", "Illinois"},
	{"US", "IN", "Indiana"},
	{"US", "IA", "Iowa"},
	{"US", "KS", "Kansas"},
	{"US", "KY", "Kentucky"},
	{"US", "LA", "Louisiana"},
	{"US", "ME", "Maine"},
	{"US", "MD", "Maryland"},
	{"US", "MA", "Massachusetts"},
	{"US", "MI", "Michigan"},
	{"US", "MN", "Minnesota"},
	{"US", "MS", "Mississippi"},
	{"US", "MO", "Missouri"},
	{"US", "MT", "Montana"},
	{"US", "NE", "Nebraska"},
	{"US", "NV", "Nevada"},
	{"US", "NH", "New Hampshire"},
	{"US", "NJ", "New Jersey"},
	{"US", "NM", "New Mexico"},
	{"US", "NY", "New York"},
	{"US", "NC", "North Carolina"},
	{"US", "ND", "North Dakota"},
	{"US", "OH", "Ohio"},
	{"US", "OK", "Oklahoma"},
	{"US", "OR", "Oregon"},
	{"US", "PA", "Pennsylvania"},
	{"US", "RI", "Rhode Island"},
	{"US", "SC", "South Carolina"},
	{"US", "SD", "South Dakota"},
	{"US", "TN", "Tennessee"},
	{"US", "TX", "Texas"},
	{"US", "UT", "Utah"},
	{"US", "VT", "Vermont"},
	{"US", "VA", "Virginia"},
	{"US", "WA", "Washington"},
	{"US", "WV", "West Virginia"},
	{"US", "WI", "Wisconsin"},
	{"US", "WY", "Wyoming"},
	{"US", "XX", "Terretories"},
