	{"AF", "AO", "Angola"},
	{"AF", "BF", "Burkina Faso"},
	{"AF", "BI", "Burundi"},
	{"AF", "BJ", "Benin"},
	{"AF", "BW", "Botswana"},
	{"AF", "CF", "Central African Republic"},
	{"AF", "CG", "Congo"},
	{"AF", "CI", "Ivory Coast"},
	{"AF", "CM", "Cameroon"},
	{"AF", "CV", "Cape Verde"},
	{"AF", "DJ", "Djibouti"},
	{"AF", "DZ", "Algeria"},
	{"AF", "EG", "Egypt"},
	{"AF", "EH", "Western Sahara"},
	{"AF", "ET", "Ethiopia"},
	{"AF", "GA", "Gabon"},
	{"AF", "GH", "Ghana"},
	{"AF", "GM", "Gambia"},
	{"AF", "GN", "Guinea"},
	{"AF", "GQ", "Equatorial Guinea"},
	{"AF", "GW", "Guinea-Bissau"},
	{"AF", "KE", "Kenya"},
	{"AF", "KM", "Comoros"},
	{"AF", "LR", "Liberia"},
	{"AF", "LS", "Lesotho"},
	{"AF", "LY", "Libya"},
	{"AF", "MA", "Morocco"},
	{"AF", "MG", "Madagascar"},
	{"AF", "ML", "Mali"},
	{"AF", "MR", "Mauritania"},
	{"AF", "MU", "Mauritius"},
	{"AF", "MW", "Malawi"},
	{"AF", "MZ", "Mozambique"},
	{"AF", "NA", "Namibia"},
	{"AF", "NE", "Niger"},
	{"AF", "NG", "Nigeria"},
	{"AF", "RE", "Reunion"},
	{"AF", "RW", "Rwanda"},
	{"AF", "SC", "Seychelles"},
	{"AF", "SD", "Sudan"},
	{"AF", "SH", "St. Helena"},
	{"AF", "SL", "Sierra Leone"},
	{"AF", "SN", "Senegal"},
	{"AF", "SO", "Somalia"},
	{"AF", "ST", "Sao"},
	{"AF", "SZ", "Swaziland"},
	{"AF", "TD", "Chad"},
	{"AF", "TG", "Togo"},
	{"AF", "TN", "Tunisia"},
	{"AF", "TZ", "Tanzania"},
	{"AF", "UG", "Uganda"},
	{"AF", "YT", "Mayotte"},
	{"AF", "ZA", "South Africa"},
	{"AF", "ZM", "Zambia"},
	{"AF", "ZR", "Zaire"},
	{"AF", "ZW", "Zimbabwe"},
	{"AN", "AQ", "Antarctica"},
	{"AS", "AE", "United Arab Emirates"},
	{"AS", "AF", "Afghanistan"},
	{"AS", "AM", "Armenia"},
	{"AS", "AZ", "Azerbaijan"},
	{"AS", "BD", "Bangladesh"},
	{"AS", "BH", "Bahrain"},
	{"AS", "BN", "Brunei"},
	{"AS", "BT", "Bhutan"},
	{"AS", "CN", "China"},
	{"AS", "CX", "Christmas Island"},
	{"AS", "GE", "Georgia"},
	{"AS", "HK", "Hong Kong"},
	{"AS", "IL", "Israel"},
	{"AS", "PS", "Palestine"},
	{"AS", "IN", "India"},
	{"AS", "IQ", "Iraq"},
	{"AS", "IR", "Iran"},
	{"AS", "JO", "Jordan"},
	{"AS", "JP", "Japan"},
	{"AS", "KG", "Kyrgyzstan"},
	{"AS", "KH", "Cambodia"},
	{"AS", "KP", "North Korea"},
	{"AS", "KR", "South Korea"},
	{"AS", "KW", "Kuwait"},
	{"AS", "KZ", "Kazakhstan"},
	{"AS", "LA", "Laos"},
	{"AS", "ID", "Indonesia"},
	{"AS", "LB", "Lebanon"},
	{"AS", "LK", "Sri Lanka"},
	{"AS", "MM", "Burma Myanmar"},
	{"AS", "MN", "Mongolia"},
	{"AS", "MO", "Macau"},
	{"AS", "MV", "Maldives"},
	{"AS", "MY", "Malaysia"},
	{"AS", "NP", "Nepal"},
	{"AS", "OM", "Oman"},
	{"AS", "PH", "Philippines"},
	{"AS", "PK", "Pakistan"},
	{"AS", "QA", "Qatar"},
	{"AS", "RU", "Russia"},
	{"AS", "SA", "Saudi Arabia"},
	{"AS", "SG", "Singapore"},
	{"AS", "SY", "Syria"},
	{"AS", "TH", "Thailand"},
	{"AS", "TJ", "Tajikistan"},
	{"AS", "TM", "Turkmenistan"},
	{"AS", "TR", "Turkey"},
	{"AS", "TW", "Taiwan"},
	{"AS", "UA", "Ukraine"},
	{"AS", "UZ", "Uzbekistan"},
	{"AS", "VN", "Vietnam"},
	{"AS", "YE", "Yemen"},
	{"EU", "AD", "Andorra"},
	{"EU", "AL", "Albania"},
	{"EU", "AT", "Austria"},
	{"EU", "BA", "Bosnia and Herzegovina"},
	{"EU", "BE", "Belgium"},
	{"EU", "BG", "Bulgaria"},
	{"EU", "BY", "Belarus"},
	{"EU", "CH", "Switzerland"},
	{"EU", "CY", "Cyprus"},
	{"EU", "CZ", "Czech Republic"},
	{"EU", "DE", "Germany"},
	{"EU", "DK", "Denmark"},
	{"EU", "EE", "Estonia"},
	{"EU", "ES", "Spain"},
	{"EU", "FI", "Finland"},
	{"EU", "FO", "Faeroe Islands"},
	{"EU", "FR", "France"},
	{"EU", "GI", "Gibraltar"},
	{"EU", "GL", "Greenland"},
	{"EU", "GR", "Greece"},
	{"EU", "HR", "Croatia"},
	{"EU", "YU", "Serbia and Montenegro"},
	{"EU", "HU", "Hungary"},
	{"EU", "IE", "Ireland"},
	{"EU", "IS", "Iceland"},
	{"EU", "IT", "Italy"},
	{"EU", "LI", "Liechtenstein"},
	{"EU", "LT", "Lithuania"},
	{"EU", "LU", "Luxembourg"},
	{"EU", "LV", "Latvia"},
	{"EU", "MC", "Monaco"},
	{"EU", "MD", "Moldova"},
	{"EU", "MK", "Macedonia"},
	{"EU", "MT", "Malta"},
	{"EU", "NL", "Netherlands"},
	{"EU", "NO", "Norway"},
	{"EU", "PL", "Poland"},
	{"EU", "PT", "Portugal"},
	{"EU", "RO", "Romania"},
	{"EU", "SE", "Sweden"},
	{"EU", "SI", "Slovenia"},
	{"EU", "SJ", "Jan Mayen"},
	{"EU", "SJ", "Svalbard"},
	{"EU", "SK", "Slovak Republic"},
	{"EU", "SM", "San Marino"},
	{"EU", "UK", "United Kingdom"},
	{"OC", "AU", "Australia"},
	{"OC", "CC", "Cocos Islands"},
	{"OC", "CK", "Cook Islands"},
	{"OC", "FJ", "Fiji"},
	{"OC", "FM", "Micronesia"},
	{"OC", "GU", "Guam"},
	{"OC", "KI", "Kiribati"},
	{"OC", "MP", "Mariana"},
	{"OC", "NC", "New Caledonia"},
	{"OC", "NF", "Norfolk Island"},
	{"OC", "NR", "Nauru"},
	{"OC", "NU", "Niue"},
	{"OC", "NZ", "New Zealand"},
	{"OC", "PF", "French Polynesia"},
	{"OC", "PG", "Papua New Guinea"},
	{"OC", "PN", "Pitcairn Island"},
	{"OC", "PW", "Republic of Palau"},
	{"OC", "Sb", "Solomon Islands"},
	{"OC", "TO", "Tonga"},
	{"OC", "TV", "Tuvalu"},
	{"OC", "VU", "Vanuatu"},
	{"OC", "WF", "Wallis"},
	{"OC", "WS", "Western Samoa"},
	{"OC", "AS", "American Samoa"},
	{"NA", "CA", "Canada"},
	{"NA", "MX", "Mexico"},
	{"NA", "US", "United States"},
	{"SA", "AG", "Antigua"},
	{"SA", "AI", "Anguilla"},
	{"SA", "AN", "Netherlands Antilles"},
	{"SA", "AR", "Argentina"},
	{"SA", "BB", "Barbados"},
	{"SA", "BM", "Bermuda"},
	{"SA", "BO", "Bolivia"},
	{"SA", "BR", "Brazil"},
	{"SA", "BS", "Bahamas"},
	{"SA", "BZ", "Belize"},
	{"SA", "CL", "Chile"},
	{"SA", "CO", "Colombia"},
	{"SA", "CR", "Costa Rica"},
	{"SA", "CU", "Cuba"},
	{"SA", "DM", "Dominica"},
	{"SA", "DO", "Dominican Republic"},
	{"SA", "EC", "Ecuador"},
	{"SA", "FK", "Falkland Islands"},
	{"SA", "GD", "Grenada"},
	{"SA", "GF", "French Guiana"},
	{"SA", "GP", "Guadeloupe"},
	{"SA", "GT", "Guatemala"},
	{"SA", "GY", "Guyana"},
	{"SA", "HN", "Honduras"},
	{"SA", "HT", "Haiti"},
	{"SA", "JM", "Jamaica"},
	{"SA", "KY", "Cayman Islands"},
	{"SA", "LC", "St. Lucia"},
	{"SA", "MQ", "Martinique"},
	{"SA", "MS", "Montserrat"},
	{"SA", "NI", "Nicaragua"},
	{"SA", "PA", "Panama"},
	{"SA", "PE", "Peru"},
	{"SA", "PR", "Puerto Rico"},
	{"SA", "PY", "Paraguay"},
	{"SA", "SR", "Surinam"},
	{"SA", "SV", "El Salvador"},
	{"SA", "TT", "Trinidad"},
	{"SA", "UY", "Uruguay"},
	{"SA", "VC", "St. Vincent"},
	{"SA", "VE", "Venezuela"},
	{"SA", "VG", "British Virgin Islands"},
	{"SA", "VI", "Virgin Islands"},
	{"XX", "JN", "Juan de Nova"},
	{"XX", "PI", "Paracel Islands"},
	{"XX", "SS", "Spratly Islands"},
	{"XX", "PM", "St. Pierre"},
	{"XX", "TI", "Tromelin Island"},
