#!/bin/sh
#
#	$Id: gmtget,v 1.1 2009-05-21 14:55:17 remko Exp $
#
#	gmtget - Return the current setting of the specified parameter
#
if [ ${#} -ne 1 ]; then
	echo "usage: gmtget PARAMETER" >&2
	exit -1
fi
gmtdefaults -L | grep "^${1}	" | awk '{print $3}'
