"/ISO-8859-3_Encoding [\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/space		/exclam		/quotedbl	/numbersign	/dollar		/percent	/ampersand	/quoteright\n\
/parenleft	/parenright	/asterisk	/plus		/comma		/hyphen		/period		/slash\n\
/zero		/one		/two		/three		/four		/five		/six		/seven\n\
/eight		/nine		/colon		/semicolon	/less		/equal		/greater	/question\n\
/at		/A		/B		/C		/D		/E		/F		/G\n\
/H		/I		/J		/K		/L		/M		/N		/O\n\
/P		/Q		/R		/S		/T		/U		/V		/W\n\
/X		/Y		/Z		/bracketleft	/backslash	/bracketright	/asciicircum	/underscore\n\
/quoteleft	/a		/b		/c		/d		/e		/f		/g\n\
/h		/i		/j		/k		/l		/m		/n		/o\n\
/p		/q		/r		/s		/t		/u		/v		/w\n\
/x		/y		/z		/braceleft	/bar		/braceright	/tilde		/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef	/.notdef\n\
/space		/Hstroke	/breve		/sterling	/currency	/yen		/Hcircumflex	/section\n\
/dieresis	/Idot		/Scedilla	/Gbreve		/Jcircumflex	/hyphen		/registered	/Zdot\n\
/degree		/hstroke	/twosuperior	/threesuperior	/acute		/mu		/hcircumflex	/bullet\n\
/cedilla	/dotlessi	/scedilla	/gbreve		/jcircumflex	/onehalf	/threequarters	/zdot\n\
/Agrave		/Aacute		/Acircumflex	/Atilde		/Adieresis	/Cdot		/Ccircumflex	/Ccedilla\n\
/Egrave		/Eacute		/Ecircumflex	/Edieresis	/Igrave		/Iacute		/Icircumflex	/Idieresis\n\
/Eth		/Ntilde		/Ograve		/Oacute		/Ocircumflex	/Gdot		/Odieresis	/multiply\n\
/Gcircumflex	/Ugrave		/Uacute		/Ucircumflex	/Udieresis	/Ubreve		/Scircumflex	/germandbls\n\
/agrave		/aacute		/acircumflex	/atilde		/adieresis	/cdot		/ccircumflex	/ccedilla\n\
/egrave		/eacute		/ecircumflex	/edieresis	/igrave		/iacute		/icircumflex	/idieresis\n\
/eth		/ntilde		/ograve		/oacute		/ocircumflex	/gdot		/odieresis	/divide\n\
/gcircumflex	/ugrave		/uacute		/ucircumflex	/udieresis	/ubreve		/scircumflex	/dotaccent\n\
] def\n",
