#
# Compile GMT, build documentation and run tests
#
name: Tests

# Only build PRs, the master and 6.x branches, and releases.
on:
  pull_request:
  push:
    branches:
      - master
      - 6.[0-9]+
  release:
    types:
      - published
  # schedule daily jobs
  schedule:
    - cron: '0 12 * * *'

defaults:
  run:
    # default to use bash shell
    shell: bash

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      COASTLINEDIR: ${{ github.workspace }}/coastline
      INSTALLDIR: ${{ github.workspace }}/gmt-install-dir
      # disable auto-display of GMT plots
      GMT_END_SHOW: off

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - name: Linux - Compile only
            os: ubuntu-latest
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : false

          - name: Linux - Compile only (without GDAL et al.)
            os: ubuntu-latest
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : false
            EXCLUDE_OPTIONAL : true

          - name: Linux - Build docs + Deploy docs + Package
            os: ubuntu-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : true
            DEPLOY_DOCS : true
            PACKAGE     : true
            RUN_TESTS   : false

          - name: Linux - Tests
            os: ubuntu-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : true

          # macOS
          - name: macOS - Compile only
            os: macos-latest
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : false

          - name: macOS - Build docs + Deploy docs + Package
            os: macos-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : true
            DEPLOY_DOCS : false
            PACKAGE     : true
            RUN_TESTS   : false

          - name: macOS - Tests
            os: macos-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : true

          # Windows
          - name: Windows - Compile only
            os: windows-latest
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : false

          - name: Windows - Build Docs + Package
            os: windows-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : true
            DEPLOY_DOCS : false
            PACKAGE     : true
            RUN_TESTS   : false

          - name: Windows - Tests
            os: windows-latest
            if: github.event_name != 'pull_request'
            BUILD_DOCS  : false
            DEPLOY_DOCS : false
            PACKAGE     : false
            RUN_TESTS   : true

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg (Windows)
        uses: dawidd6/action-download-artifact@v2.10.0
        with:
          workflow: ci-caches.yml
          name: vcpkg-cache
          path: C:\vcpkg\installed\
        if: runner.os == 'Windows'

      - name: Install GMT dependencies
        run: |
          # $RUNNER_OS can be Linux, macOS or Windows
          # The following command converts $RUNNER_OS to lowercase
          os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          bash ci/install-dependencies-${os}.sh
        env:
          RUN_TESTS: ${{ matrix.RUN_TESTS }}
          BUILD_DOCS: ${{ matrix.BUILD_DOCS }}
          PACKAGE: ${{ matrix.PACKAGE }}
          EXCLUDE_OPTIONAL : ${{ matrix.EXCLUDE_OPTIONAL }}

      - name: Cache GSHHG and DCW data
        uses: actions/cache@v2
        id: cache-coastline
        with:
          path: ${{ env.COASTLINEDIR }}
          key: coastline-${{ hashFiles('ci/download-coastlines.sh') }}

      - name: Download coastlines
        run: bash ci/download-coastlines.sh
        if: steps.cache-coastline.outputs.cache-hit != 'true'

      - name: Configure GMT
        run: |
          if [ "$RUNNER_OS" != "Windows" ]; then
            bash ci/config-gmt-unix.sh
          else
            bash ci/config-gmt-windows.sh
          fi
        env:
          RUN_TESTS: ${{ matrix.RUN_TESTS }}
          BUILD_DOCS: ${{ matrix.BUILD_DOCS }}

      - name: Compile GMT (Linux/macOS)
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          cmake --build .
        if: runner.os != 'Windows'

      - name: Compile GMT (Windows)
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .
        if: runner.os == 'Windows'

      - name: Download cached GMT remote data from GitHub Artifacts
        uses: dawidd6/action-download-artifact@v2.10.0
        with:
          workflow: ci-caches.yml
          name: gmt-cache
          path: .gmt

      # Move downloaded files to ~/.gmt directory and list them
      - name: Move and list downloaded remote files
        run: |
          mkdir -p ~/.gmt
          mv .gmt/* ~/.gmt
          ls -lRh ~/.gmt

      - name: Build documentations
        run: |
          set -x -e
          cd build
          cmake --build . --target docs_depends
          cmake --build . --target optimize_images
          if [ "$RUNNER_OS" != "Windows" ]; then
            cmake --build . --target animation
          fi
          cmake --build . --target docs_html
          # if html.log isn't empty (i.e., sphinx raise warnings), return 1
          ! [ -s doc/rst/html.log ]
          cmake --build . --target docs_man
          # if man.log isn't empty (i.e., sphinx raise warnings), return 1
          ! [ -s doc/rst/man.log ]
        if: matrix.BUILD_DOCS == true

      - name: Install GMT
        run: |
          cd build
          cmake --build . --target install
          # Add GMT PATH to bin
          echo "${INSTALLDIR}/bin" >> $GITHUB_PATH

      - name: Check a few simple commands
        run: |
          set -x -e
          gmt --version
          gmt-config --all
          gmt defaults -Vd
          gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test.ps
          gmt begin && gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd && gmt end
          gmt grdimage @earth_relief_01d -JH10c -Baf -pdf map
          gmt earthtide -T2018-06-18T12:00:00 -Gsolid_tide_up.grd

      - name: Check a few simple commands (Windows)
        shell: cmd
        run: |
          gmt --version
          bash %INSTALLDIR%/bin/gmt-config --all
          gmt defaults -Vd
          gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test.ps
          gmt begin && gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd && gmt end
          gmt grdimage @earth_relief_01d -JH10c -Baf -pdf map
          gmt earthtide -T2018-06-18T12:00:00 -Gsolid_tide_up.grd
        if: runner.os == 'Windows'

      # Run full tests and rerun failed tests
      - name: Run full tests
        run: |
          set -x -e
          cd build
          # Disable MinGW's path conversion, see #1035.
          if [ "$RUNNER_OS" == "Windows" ]; then export MSYS_NO_PATHCONV=1; fi
          # Run tests
          ctest ${CTEST_ARGS} || ctest ${CTEST_ARGS} --rerun-failed || ctest ${CTEST_ARGS} --rerun-failed
        env:
          CTEST_ARGS : "--output-on-failure --force-new-ctest-process -j4 --timeout 480"
        if: matrix.RUN_TESTS == true

      - name: Run DOS batch examples (Windows)
        shell: cmd
        run: |
          cd doc/examples
          call do_examples.bat
        if: ${{ matrix.RUN_TESTS == true && runner.os == 'Windows' }}

      - name: Upload build directory if failed
        uses: actions/upload-artifact@v2
        with:
          name: BuildDirectory-${{ runner.os }}
          path: build/
        if: ${{ failure() }}

      # Upload test coverage even if build fails
      - name: Upload test coverage
        run: |
          set -x -e
          bash <(curl -s https://codecov.io/bash)
        if: ${{ matrix.RUN_TESTS == true && always() }}

      - name: Checkout the gh-pages branch in a separate folder
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
        with:
          ref: gh-pages
          # Checkout to this folder instead of the current one
          path: deploy
          # Download the entire history
          fetch-depth: 0
        if: matrix.DEPLOY_DOCS == true

      - name: Deploy documentation to GitHub
        run: bash ci/deploy-gh-pages.sh
        if: matrix.DEPLOY_DOCS == true

      - name: Package GMT
        run: |
          set -x -e
          cd build
          cmake --build . --target gmt_release
          cmake --build . --target gmt_release_tar
          if [ "$RUNNER_OS" = "macOS" ]; then
            # Create macOS bundle
            cpack -G Bundle
          elif [ "$RUNNER_OS" = "Windows" ]; then
            # Don't use cpack here. Chocolatey also provides a cpack command.
            cmake --build . --target package
          fi
        if: matrix.PACKAGE == true

