# Workflow to run cppchecks

on:
  # enable pull request for debugging
  #pull_request:
  # Schedule runs daily
  schedule:
    - cron: '0 0 * * *'

name: Lint Checker

jobs:
  lint-checker:
    name: Lint Checker
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: |
        set -x -e
        #sudo snap install cppcheck
        # Install the dev version due to a packaging issue of cppcheck 2.3
        sudo snap install cppcheck --edge
        cppcheck --version

    - name: Run cppcheck
      run: bash admin/run_cppcheck.sh src
