Attributes {
    bears {
        String act "text string\\012\\011123";
        Int16 acs -40;
        Int32 acl 17000;
        Float32 acf -2.000000000, 1.000000000, 0.000000000;
        Float64 acd -1.0000000000000000, 0.75000000000000000;
        Int32 string_length 3;
    }
    order {
    }
    shot {
    }
    aloan {
    }
    cross {
    }
    i {
        String attr1 "1";
        String attr2 "1", "2", "3", "4";
        i_1 {
            String attr3_1 "17";
            Float64 attr3_2 19, 23, 27;
        }
    }
    j {
    }
    l {
    }
    NC_GLOBAL {
        String history "This is an example of a multi-line global\\012attribute.  It could be used for representing the\\012processing history of the data, for example.";
    }
    DODS_EXTRA {
        String Unlimited_Dimension "k";
    }
}
