Attributes {
    humans {
        String position "There are too many humans.";
        String offer "Here are a few...";
    }
    b31 {
        class {
            String long_name "class is dismissed";
            String short_name "cid", "kid", "bid", "did";
            text {
                String long_name "textually yours";
                String short_name "ty";
            }
        }
        foo {
            String long_name "It is beyond all recognition";
            String short_name "foobar";
            String SS_number "304-66-9876";
        }
    }
    b32 {
        String billy "Bob is my real name";
        String Robert "Really wants to be called Billy";
    }
}
