Attributes {
    Facility {
        String PrincipleInvestigator "Mark Abbott", "Ph.D";
        String DataCenter "COAS Environmental Computer Facility";
        String DrifterType "MetOcean WOCE/OCM";
    }
    b {
        String Description "A test byte";
        String units "unknown";
    }
    i32 {
        String Description "A 32 bit test server int";
        String units "unknown";
    }
}
